use super::{ManifestBaseline, ManifestCount};

/// Builds one static manifest counter expectation.
///
/// Inputs:
/// - `field`: JSON field name under `core_proof_coverage`.
/// - `expected`: expected unsigned integer value for that field.
///
/// Output:
/// - `ManifestCount` with the provided field and expected value.
///
/// Transformation:
/// - Wraps the field/value pair in the baseline counter type without allocation.
const fn count(field: &'static str, expected: u64) -> ManifestCount {
    ManifestCount { field, expected }
}

/// Names every unresolved-constructor manifest counter required to be zero.
///
/// Inputs:
/// - No runtime input.
///
/// Output:
/// - Static field-name slice for call, chain, and pattern unresolved
///   constructor counters.
///
/// Transformation:
/// - Centralizes the constructor-resolution field list used by baseline-shape
///   tests without allocating or inspecting manifest artifacts.
pub(crate) const UNRESOLVED_CONSTRUCTOR_COUNTER_FIELDS: &[&str] = &[
    "unresolved_constructor_call_candidate",
    "unresolved_constructor_chain_candidate",
    "unresolved_constructor_pattern_candidate",
];

/// Names every resolved-constructor manifest counter required by baselines.
///
/// Inputs:
/// - No runtime input.
///
/// Output:
/// - Static field-name slice for call, chain, and pattern resolved constructor
///   identity counters.
///
/// Transformation:
/// - Centralizes the constructor-identity field list used by baseline-shape
///   tests without allocating or inspecting manifest artifacts.
pub(crate) const RESOLVED_CONSTRUCTOR_COUNTER_FIELDS: &[&str] = &[
    "resolved_constructor_call_identity",
    "resolved_constructor_chain_identity",
    "resolved_constructor_pattern_identity",
];

const PHASE_BASIC_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_CORE_LEAN_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 1),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 1),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 2),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 1),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 1),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 1),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_ATOM_LITERAL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 1),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 1),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 1),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 1),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 1),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_INT_LITERAL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 1),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 1),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 1),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 1),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 1),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_CORE_LAMBDA_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 2),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 2),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 2),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 2),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 1),
    count("checked_preservation_expr_runtime_bindings_required", 1),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_CONSTRUCTOR_RESOLUTION_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 1),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_CONSTRUCTOR_PATTERN_RESOLUTION_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 4),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 2),
    count("checked_preservation_expr_runtime_bindings_required", 1),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 1),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_LITERAL_PATTERN_CASE_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 4),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 4),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 2),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 4),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 4),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 4),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_UNARY_OPERATOR_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 2),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 2),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 2),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 2),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 2),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 2),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_LIST_CONS_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_IF_EXPR_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 2),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_FIELD_ACCESS_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 2),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 2),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 2),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 2),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 2),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_LITERAL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 1),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 1),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 1),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 1),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 1),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_TUPLE_LITERAL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_LIST_LITERAL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 0),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 0),
    count("summary_only_pattern", 0),
    count("typed_core_type", 1),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 0),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 0),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 0),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_NAMED_CALL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 4),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 1),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 4),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 1),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 4),
    count("checked_preservation_pattern", 1),
    count("checked_preservation_expr_structural", 4),
    count("checked_preservation_pattern_structural", 1),
    count("checked_preservation_expr_no_runtime_bindings", 4),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 1),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_EQ_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_LT_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_LTE_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_GT_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_GTE_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_MUL_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_BINARY_SUB_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 0),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 3),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 3),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 3),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 3),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const PHASE_TRAIT_MANIFEST_COUNTS: &[ManifestCount] = &[
    count("lean_covered", 3),
    count("partial", 0),
    count("proof_model_required", 1),
    count("runtime_boundary", 0),
    count("artifact_only", 0),
    count("pattern_lean_covered", 2),
    count("pattern_partial", 0),
    count("pattern_proof_model_required", 0),
    count("pattern_runtime_boundary", 0),
    count("pattern_artifact_only", 0),
    count("typed_core_expr", 4),
    count("summary_only_expr", 0),
    count("typed_core_pattern", 2),
    count("summary_only_pattern", 0),
    count("typed_core_type", 3),
    count("summary_only_type", 0),
    count("checked_preservation_expr", 4),
    count("checked_preservation_pattern", 2),
    count("checked_preservation_expr_structural", 4),
    count("checked_preservation_pattern_structural", 2),
    count("checked_preservation_expr_no_runtime_bindings", 4),
    count("checked_preservation_expr_runtime_bindings_required", 0),
    count("checked_preservation_pattern_no_runtime_bindings", 0),
    count("checked_preservation_pattern_runtime_bindings_required", 2),
    count("resolved_constructor_call_identity", 0),
    count("resolved_constructor_chain_identity", 0),
    count("resolved_constructor_pattern_identity", 0),
    count("unresolved_constructor_call_candidate", 0),
    count("unresolved_constructor_chain_candidate", 0),
    count("unresolved_constructor_pattern_candidate", 0),
];

const MANIFEST_BASELINES: &[ManifestBaseline] = &[
    ManifestBaseline {
        module_name: "phase_basic",
        counts: PHASE_BASIC_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_eq",
        counts: PHASE_BINARY_EQ_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_lt",
        counts: PHASE_BINARY_LT_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_lte",
        counts: PHASE_BINARY_LTE_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_gt",
        counts: PHASE_BINARY_GT_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_gte",
        counts: PHASE_BINARY_GTE_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_mul",
        counts: PHASE_BINARY_MUL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_sub",
        counts: PHASE_BINARY_SUB_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_core_lean",
        counts: PHASE_CORE_LEAN_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_int_literal",
        counts: PHASE_INT_LITERAL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_atom_literal",
        counts: PHASE_ATOM_LITERAL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_binary_literal",
        counts: PHASE_BINARY_LITERAL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_tuple_literal",
        counts: PHASE_TUPLE_LITERAL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_list_literal",
        counts: PHASE_LIST_LITERAL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_named_call",
        counts: PHASE_NAMED_CALL_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_unary_operator",
        counts: PHASE_UNARY_OPERATOR_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_core_lambda",
        counts: PHASE_CORE_LAMBDA_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_constructor_resolution",
        counts: PHASE_CONSTRUCTOR_RESOLUTION_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_constructor_pattern_resolution",
        counts: PHASE_CONSTRUCTOR_PATTERN_RESOLUTION_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_literal_pattern_case",
        counts: PHASE_LITERAL_PATTERN_CASE_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_list_cons",
        counts: PHASE_LIST_CONS_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_if_expr",
        counts: PHASE_IF_EXPR_MANIFEST_COUNTS,
    },
    ManifestBaseline {
        module_name: "phase_field_access",
        counts: PHASE_FIELD_ACCESS_MANIFEST_COUNTS,
    },
];

const NEXT_MODEL_CANDIDATE_MANIFEST_BASELINES: &[ManifestBaseline] = &[ManifestBaseline {
    module_name: "phase_trait",
    counts: PHASE_TRAIT_MANIFEST_COUNTS,
}];

/// Returns the gate-backed phase-manifest baseline table.
///
/// Inputs:
/// - None.
///
/// Output:
/// - Static slice of LP8 compiler fixtures and their expected
///   `core_proof_coverage` counters.
///
/// Transformation:
/// - Exposes immutable proof-counter expectations for callers that already know
///   how to run `check --emit-phase-manifest` and decode JSON.
pub(crate) const fn manifest_baselines() -> &'static [ManifestBaseline] {
    MANIFEST_BASELINES
}

/// Returns phase-manifest baselines for the next Lean model candidates.
///
/// Inputs:
/// - None.
///
/// Output:
/// - Static slice of compiler fixtures and expected `core_proof_coverage`
///   counters for typed forms that are intentionally not Lean-covered yet.
///
/// Transformation:
/// - Exposes immutable candidate proof-counter expectations for callers that
///   already know how to run `check --emit-phase-manifest` and decode JSON.
pub(crate) const fn next_lean_model_candidate_manifest_baselines() -> &'static [ManifestBaseline] {
    NEXT_MODEL_CANDIDATE_MANIFEST_BASELINES
}
