mod comprehension;
mod declarations;
mod html;
mod let_else;
mod literals;
mod metadata;
mod repeated_lets;
include!("formatter_part_001.rs");
include!("formatter_part_002.rs");
include!("formatter_part_003.rs");
include!("formatter_part_004.rs");
