//! Packaged standard interfaces and their exact dependency manifests.
//!
//! One catalogue binds each implementation summary to its dependency closure.
//! Namespace-only summaries have no implementation dependency manifest.

pub(super) struct EmbeddedStdInterface {
    pub(super) module: &'static str,
    pub(super) summary: &'static str,
    pub(super) dependencies: Option<&'static str>,
}

macro_rules! embedded {
    ($module:literal) => {
        EmbeddedStdInterface {
            module: $module,
            summary: include_str!(concat!("../../../../std/summaries/", $module, ".typi")),
            dependencies: Some(include_str!(concat!(
                "../../../../std/summaries/",
                $module,
                ".typi.deps"
            ))),
        }
    };
}

macro_rules! namespace {
    ($module:literal) => {
        EmbeddedStdInterface {
            module: $module,
            summary: include_str!(concat!("../../../../std/summaries/", $module, ".typi")),
            dependencies: None,
        }
    };
}

pub(super) const EMBEDDED_STD_INTERFACES: &[EmbeddedStdInterface] = &[
    embedded!("std.vm.Agent"),
    embedded!("std.vm.Backpressure"),
    embedded!("std.vm.BitString"),
    embedded!("std.vm.Bytes"),
    embedded!("std.vm.Cluster"),
    embedded!("std.vm.DistributedState"),
    embedded!("std.vm.DistributedStorage"),
    embedded!("std.vm.Fault"),
    embedded!("std.vm.GenServer"),
    embedded!("std.vm.Message"),
    embedded!("std.vm.ModelSync"),
    embedded!("std.vm.NativeBridge"),
    embedded!("std.vm.PersistentActor"),
    embedded!("std.vm.Port"),
    embedded!("std.vm.Process"),
    embedded!("std.vm.Scheduler"),
    embedded!("std.vm.Supervisor"),
    embedded!("std.vm.Task"),
    embedded!("std.vm.Tcp"),
    embedded!("std.vm.Timeout"),
    embedded!("std.core.Add"),
    embedded!("std.core.Atom"),
    embedded!("std.core.Bool"),
    embedded!("std.core.Effect"),
    embedded!("std.core.Equal"),
    embedded!("std.core.Error"),
    embedded!("std.core.Float"),
    embedded!("std.core.Functional"),
    embedded!("std.core.GuardResult"),
    embedded!("std.core.Int"),
    embedded!("std.core.Memory"),
    embedded!("std.core.Object"),
    embedded!("std.binary.Binary"),
    embedded!("std.collections.Enumerable"),
    embedded!("std.collections.Index"),
    embedded!("std.collections.Iterable"),
    embedded!("std.collections.Iterator"),
    embedded!("std.collections.KeyedEnumerable"),
    embedded!("std.collections.List"),
    embedded!("std.collections.Map"),
    embedded!("std.data.Json"),
    embedded!("std.data.Toml"),
    embedded!("std.db.Postgres"),
    embedded!("std.crypto.Hash"),
    embedded!("std.crypto.Ed25519"),
    embedded!("std.encoding.Base64"),
    embedded!("std.encoding.Md5"),
    namespace!("std.http"),
    embedded!("std.http.Cookies"),
    embedded!("std.http.Error"),
    embedded!("std.http.Request"),
    embedded!("std.http.Response"),
    embedded!("std.http.Router"),
    embedded!("std.http.Session"),
    embedded!("std.http.Sse"),
    embedded!("std.http.WebSocket"),
    embedded!("std.http.Tls"),
    embedded!("std.native.collections.Vector"),
    embedded!("std.core.Option"),
    embedded!("std.core.Ordering"),
    embedded!("std.core.Result"),
    embedded!("std.core.Secret"),
    embedded!("std.collections.Set"),
    embedded!("std.range.Range"),
    embedded!("std.random.Random"),
    embedded!("std.regex.Regex"),
    embedded!("std.package.Registry"),
    embedded!("std.core.String"),
    embedded!("std.core.Task"),
    embedded!("std.core.Unit"),
    namespace!("std.core"),
    embedded!("std.io.Console"),
    embedded!("std.io.Archive"),
    embedded!("std.io.Directory"),
    embedded!("std.io.File"),
    embedded!("std.io.Path"),
    namespace!("std.io"),
    embedded!("std.log.Field"),
    embedded!("std.log.Log"),
    embedded!("std.service.Config"),
    embedded!("std.service.Context"),
    embedded!("std.service.Lifecycle"),
    embedded!("std.service.Metrics"),
    embedded!("std.service.Trace"),
    embedded!("std.js.Array"),
    embedded!("std.js.Dom.Document"),
    embedded!("std.js.Dom.HTMLElement"),
    embedded!("std.js.Number"),
    embedded!("std.js.Promise"),
    embedded!("std.js.String"),
    embedded!("std.net.Uri"),
    embedded!("std.sync.Resource"),
    embedded!("std.system.Arguments"),
    embedded!("std.system.Environment"),
    embedded!("std.system.Process"),
    embedded!("std.system.Platform"),
    embedded!("std.template.Template"),
    embedded!("std.test.Gen"),
    embedded!("std.test.Shrink"),
    embedded!("std.test.Test"),
    namespace!("std.time"),
    embedded!("std.time.Clock"),
    embedded!("std.time.Date"),
    embedded!("std.time.Duration"),
    embedded!("std.time.Instant"),
    embedded!("std.vcs.Git"),
    embedded!("std.wasm.Abi"),
];
