// Run from the repository root:
// rustc tree-sitter-terlan/scripts/sql_identifier_ranges.rs -o target/sql-identifier-ranges
// target/sql-identifier-ranges > tree-sitter-terlan/src/sql_identifier_ranges.h
fn main() {
    println!("// Generated by scripts/sql_identifier_ranges.rs; do not edit.");
    println!("// Rust Unicode version: {:?}", char::UNICODE_VERSION);
    println!("static const int32_t sql_identifier_ranges[][2] = {{");
    let mut start = None;
    for value in 0x80..=0x110000 {
        let matches = char::from_u32(value).is_some_and(char::is_alphanumeric);
        match (start, matches) {
            (None, true) => start = Some(value),
            (Some(first), false) => {
                println!("  {{0x{first:X}, 0x{:X}}},", value - 1);
                start = None;
            }
            _ => {}
        }
    }
    println!("}};");
}
