
/// Verifies VM WebSocket sessions account text traffic over VM TCP.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - One client text frame and one server text frame.
///
/// Output:
/// - Test passes when received/sent frame and byte counters match the VM TCP
///   traffic.
///
/// Transformation:
/// - Proves session inspection is VM-owned while frame bytes still round-trip
///   through maintained tungstenite encoding.
#[test]
fn vm_websocket_session_tracks_text_traffic() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let incoming = encode_client_text_frame("session in");
    let incoming_len = incoming.len();
    tcp.send(client, incoming).expect("send client text frame");

    let received = session
        .receive_text(&mut tcp, 4096)
        .expect("receive session text")
        .expect("queued session text");

    assert_eq!(received, "session in");
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: incoming_len,
        }
    );

    let written = session
        .send_text(&mut tcp, "session out")
        .expect("send session text");
    let outgoing = tcp
        .receive(client, written)
        .expect("receive server text frame")
        .expect("queued server text frame");

    assert_eq!(decode_server_text_frame(&outgoing), "session out");
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 1,
            frames_received: 1,
            bytes_sent: written,
            bytes_received: incoming_len,
        }
    );
}

/// Verifies received close control frames close the VM WebSocket session.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - Client close frame generated by tungstenite.
///
/// Output:
/// - Test passes when the session becomes closed and later sends are rejected.
///
/// Transformation:
/// - Keeps WebSocket lifecycle state in the VM rather than in the transport
///   adapter.
#[test]
fn vm_websocket_session_closes_after_received_close_frame() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let close = encode_client_control_frame(VmWebSocketControlFrame::Close);
    let close_len = close.len();
    tcp.send(client, close).expect("send client close");

    let received = session
        .receive_control(&mut tcp, 4096)
        .expect("receive close")
        .expect("queued close");

    assert_eq!(received, VmWebSocketControlFrame::Close);
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: false,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: close_len,
        }
    );
    assert_eq!(
        session
            .send_text(&mut tcp, "after close")
            .expect_err("closed session send"),
        "error[vm_websocket_session]: session is closed"
    );
}

/// Verifies sending a close frame closes the VM WebSocket session.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - Server close event sent through the session.
///
/// Output:
/// - Test passes when the client decodes a close frame and the session reports
///   closed state.
///
/// Transformation:
/// - Gives higher-level WebSocket actors deterministic local lifecycle
///   semantics for close sends.
#[test]
fn vm_websocket_session_closes_after_sent_close_frame() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);

    let written = session
        .send_control(&mut tcp, VmWebSocketControlFrame::Close)
        .expect("send session close");
    let close = tcp
        .receive(client, written)
        .expect("receive close frame")
        .expect("queued close frame");

    assert_eq!(
        decode_server_control_frame(&close),
        VmWebSocketControlFrame::Close
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: false,
            frames_sent: 1,
            frames_received: 0,
            bytes_sent: written,
            bytes_received: 0,
        }
    );
    assert_eq!(
        session
            .receive_text(&mut tcp, 4096)
            .expect_err("closed session receive"),
        "error[vm_websocket_session]: session is closed"
    );
}

/// Verifies session `send_frame` emits text and control frames.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - One text event and one pong control event.
///
/// Output:
/// - Test passes when the client decodes both frames and session counters
///   account for both sends.
///
/// Transformation:
/// - Gives WebSocket actors a single send surface matching unified receive
///   semantics.
#[test]
fn vm_websocket_session_send_frame_handles_text_and_control() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);

    let text_bytes = session
        .send_frame(
            &mut tcp,
            VmWebSocketFrame::Text("send frame text".to_string()),
        )
        .expect("send text frame");
    let text = tcp
        .receive(client, text_bytes)
        .expect("receive text frame")
        .expect("queued text frame");
    let control_bytes = session
        .send_frame(
            &mut tcp,
            VmWebSocketFrame::Control(VmWebSocketControlFrame::Pong(b"pong".to_vec())),
        )
        .expect("send pong frame");
    let control = tcp
        .receive(client, control_bytes)
        .expect("receive control frame")
        .expect("queued control frame");

    assert_eq!(decode_server_text_frame(&text), "send frame text");
    assert_eq!(
        decode_server_control_frame(&control),
        VmWebSocketControlFrame::Pong(b"pong".to_vec())
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 2,
            frames_received: 0,
            bytes_sent: text_bytes + control_bytes,
            bytes_received: 0,
        }
    );
}

/// Verifies session send helpers wrap VM TCP transport failures.
///
/// Inputs:
/// - Accepted VM TCP stream cancelled before session-level sends.
///
/// Output:
/// - Test passes when text and control send helpers both report stable
///   WebSocket-layer diagnostics.
///
/// Transformation:
/// - Keeps VM WebSocket actor send failures scoped to the WebSocket API even
///   though VM TCP owns stream cancellation state.
#[test]
fn vm_websocket_session_send_helpers_wrap_transport_errors() {
    let (mut tcp, _client, server) = connected_tcp_pair();
    tcp.cancel_stream(server).expect("cancel server stream");
    let mut text_session = VmWebSocketSession::new(server);
    let mut control_session = VmWebSocketSession::new(server);

    let text_err = text_session
        .send_text(&mut tcp, "cancelled text")
        .expect_err("cancelled text send rejected");
    let control_err = control_session
        .send_control(
            &mut tcp,
            VmWebSocketControlFrame::Pong(b"cancelled".to_vec()),
        )
        .expect_err("cancelled control send rejected");

    assert_eq!(
        text_err,
        "error[vm_websocket_tcp]: failed to send text frame: VM TCP stream is cancelled"
    );
    assert_eq!(
        control_err,
        "error[vm_websocket_tcp]: failed to send control frame: VM TCP stream is cancelled"
    );
}

/// Verifies session `send_frame` applies close lifecycle semantics.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - One close control event sent through the unified send path.
///
/// Output:
/// - Test passes when the client decodes a close frame and later sends fail
///   with the stable closed-session diagnostic.
///
/// Transformation:
/// - Keeps lifecycle behavior identical between specialized and unified send
///   APIs.
#[test]
fn vm_websocket_session_send_frame_closes_on_close_event() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);

    let written = session
        .send_frame(
            &mut tcp,
            VmWebSocketFrame::Control(VmWebSocketControlFrame::Close),
        )
        .expect("send close frame");
    let close = tcp
        .receive(client, written)
        .expect("receive close frame")
        .expect("queued close frame");

    assert_eq!(
        decode_server_control_frame(&close),
        VmWebSocketControlFrame::Close
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: false,
            frames_sent: 1,
            frames_received: 0,
            bytes_sent: written,
            bytes_received: 0,
        }
    );
    assert_eq!(
        session
            .send_frame(&mut tcp, VmWebSocketFrame::Text("closed".to_string()))
            .expect_err("closed session send frame"),
        "error[vm_websocket_session]: session is closed"
    );
}

/// Verifies session `receive_frame` handles mixed text and control traffic.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - One client text frame followed by one client ping frame.
///
/// Output:
/// - Test passes when both frames are returned as typed events and counters
///   reflect both reads.
///
/// Transformation:
/// - Proves WebSocket actors can consume one ordered mixed stream without
///   guessing which specialized receive helper to call.
#[test]
fn vm_websocket_session_receive_frame_handles_mixed_stream() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let text = encode_client_text_frame("first");
    let ping = encode_client_control_frame(VmWebSocketControlFrame::Ping(b"second".to_vec()));
    let expected_bytes = text.len() + ping.len();
    tcp.send(client, text).expect("send text");
    tcp.send(client, ping).expect("send ping");

    let first = session
        .receive_frame(&mut tcp, 4096)
        .expect("receive first")
        .expect("first frame");
    let second = session
        .receive_frame(&mut tcp, 4096)
        .expect("receive second")
        .expect("second frame");

    assert_eq!(first, VmWebSocketFrame::Text("first".to_string()));
    assert_eq!(
        second,
        VmWebSocketFrame::Control(VmWebSocketControlFrame::Ping(b"second".to_vec()))
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 0,
            frames_received: 2,
            bytes_sent: 0,
            bytes_received: expected_bytes,
        }
    );
}

/// Verifies session receive helpers distinguish idle streams from TCP errors.
///
/// Inputs:
/// - Empty accepted VM TCP stream.
/// - A zero-byte receive limit rejected by the VM TCP runtime.
///
/// Output:
/// - Test passes when idle reads return `None` and invalid reads return
///   WebSocket-layer diagnostics for text, control, and unified receive paths.
///
/// Transformation:
/// - Keeps actor polling loops idempotent while preserving explicit transport
///   validation failures at the VM WebSocket boundary.
#[test]
fn vm_websocket_session_receive_helpers_handle_empty_and_invalid_reads() {
    let (mut tcp, _client, server) = connected_tcp_pair();
    let mut empty_text = VmWebSocketSession::new(server);
    let mut empty_control = VmWebSocketSession::new(server);
    let mut invalid_text = VmWebSocketSession::new(server);
    let mut invalid_control = VmWebSocketSession::new(server);
    let mut invalid_frame = VmWebSocketSession::new(server);

    assert_eq!(
        empty_text
            .receive_text(&mut tcp, 4096)
            .expect("empty text receive"),
        None
    );
    assert_eq!(
        empty_control
            .receive_control(&mut tcp, 4096)
            .expect("empty control receive"),
        None
    );
    assert_eq!(
        invalid_text
            .receive_text(&mut tcp, 0)
            .expect_err("invalid text receive"),
        "error[vm_websocket_tcp]: failed to receive text frame: VM TCP receive max_bytes must be greater than 0"
    );
    assert_eq!(
        invalid_control
            .receive_control(&mut tcp, 0)
            .expect_err("invalid control receive"),
        "error[vm_websocket_tcp]: failed to receive control frame: VM TCP receive max_bytes must be greater than 0"
    );
    assert_eq!(
        invalid_frame
            .receive_frame(&mut tcp, 0)
            .expect_err("invalid frame receive"),
        "error[vm_websocket_tcp]: failed to receive frame: VM TCP receive max_bytes must be greater than 0"
    );
}

/// Verifies session `receive_frame` applies close lifecycle semantics.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - Client close frame generated by tungstenite.
///
/// Output:
/// - Test passes when the unified receive path returns a close event and marks
///   the session closed.
///
/// Transformation:
/// - Keeps close handling consistent across specialized and unified receive
///   paths.
#[test]
fn vm_websocket_session_receive_frame_closes_on_close_event() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let close = encode_client_control_frame(VmWebSocketControlFrame::Close);
    let close_len = close.len();
    tcp.send(client, close).expect("send close");

    let event = session
        .receive_frame(&mut tcp, 4096)
        .expect("receive close")
        .expect("close event");

    assert_eq!(
        event,
        VmWebSocketFrame::Control(VmWebSocketControlFrame::Close)
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: false,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: close_len,
        }
    );
}

/// Verifies session auto-pong responds to ping frames.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - Client ping frame generated by tungstenite.
///
/// Output:
/// - Test passes when the VM returns the ping event to the caller and emits a
///   matching pong frame to the client.
///
/// Transformation:
/// - Keeps WebSocket ping boilerplate in the VM session layer rather than in
///   every actor implementation.
#[test]
fn vm_websocket_session_receive_frame_with_auto_pong_replies_to_ping() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let ping = encode_client_control_frame(VmWebSocketControlFrame::Ping(b"pulse".to_vec()));
    let ping_len = ping.len();
    tcp.send(client, ping).expect("send ping");

    let event = session
        .receive_frame_with_auto_pong(&mut tcp, 4096)
        .expect("receive ping")
        .expect("ping event");
    let pong = tcp
        .receive(client, 4096)
        .expect("receive pong")
        .expect("queued pong");
    let pong_len = pong.len();

    assert_eq!(
        event,
        VmWebSocketFrame::Control(VmWebSocketControlFrame::Ping(b"pulse".to_vec()))
    );
    assert_eq!(
        decode_server_control_frame(&pong),
        VmWebSocketControlFrame::Pong(b"pulse".to_vec())
    );
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 1,
            frames_received: 1,
            bytes_sent: pong_len,
            bytes_received: ping_len,
        }
    );
}

/// Verifies session auto-pong does not respond to data frames.
///
/// Inputs:
/// - VM TCP client/server stream pair.
/// - Client text frame generated by tungstenite.
///
/// Output:
/// - Test passes when the VM reports the text event and no frame is queued
///   back to the client.
///
/// Transformation:
/// - Keeps auto-pong behavior narrowly scoped to ping control frames.
#[test]
fn vm_websocket_session_receive_frame_with_auto_pong_ignores_text() {
    let (mut tcp, client, server) = connected_tcp_pair();
    let mut session = VmWebSocketSession::new(server);
    let text = encode_client_text_frame("plain data");
    let text_len = text.len();
    tcp.send(client, text).expect("send text");

    let event = session
        .receive_frame_with_auto_pong(&mut tcp, 4096)
        .expect("receive text")
        .expect("text event");

    assert_eq!(event, VmWebSocketFrame::Text("plain data".to_string()));
    assert_eq!(tcp.receive(client, 4096).expect("client receive"), None);
    assert_eq!(
        session.inspect(),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: text_len,
        }
    );
}

/// Verifies the VM WebSocket runtime isolates multiple sessions.
///
/// Inputs:
/// - One VM TCP runtime with two independent client/server stream pairs.
/// - One WebSocket session per accepted server stream.
///
/// Output:
/// - Test passes when each session receives only its own stream traffic and
///   inspection counters stay independent.
///
/// Transformation:
/// - Proves production WebSocket handlers can keep session ownership in the VM
///   registry instead of ad hoc HTTP-layer maps.
#[test]
fn vm_websocket_runtime_routes_sessions_independently() {
    let mut tcp = VmTcpRuntime::new();
    let (client_a, server_a) = connected_tcp_pair_at(&mut tcp, "websocket.a");
    let (client_b, server_b) = connected_tcp_pair_at(&mut tcp, "websocket.b");
    let mut runtime = VmWebSocketRuntime::new();
    let session_a = runtime.open_session(server_a);
    let session_b = runtime.open_session(server_b);
    let frame_a = encode_client_text_frame("alpha");
    let frame_b = encode_client_text_frame("beta");
    let frame_a_len = frame_a.len();
    let frame_b_len = frame_b.len();
    tcp.send(client_a, frame_a).expect("send alpha");
    tcp.send(client_b, frame_b).expect("send beta");

    let beta = runtime
        .receive_frame(&mut tcp, session_b, 4096)
        .expect("receive beta")
        .expect("queued beta");
    let alpha = runtime
        .receive_frame(&mut tcp, session_a, 4096)
        .expect("receive alpha")
        .expect("queued alpha");

    assert_eq!(runtime.session_count(), 2);
    assert_eq!(beta, VmWebSocketFrame::Text("beta".to_string()));
    assert_eq!(alpha, VmWebSocketFrame::Text("alpha".to_string()));
    assert_eq!(
        runtime.inspect_session(session_a).expect("inspect alpha"),
        VmWebSocketSessionInfo {
            stream: server_a,
            open: true,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: frame_a_len,
        }
    );
    assert_eq!(
        runtime.inspect_session(session_b).expect("inspect beta"),
        VmWebSocketSessionInfo {
            stream: server_b,
            open: true,
            frames_sent: 0,
            frames_received: 1,
            bytes_sent: 0,
            bytes_received: frame_b_len,
        }
    );
}

/// Verifies checked session open validates a live VM TCP stream.
///
/// Inputs:
/// - One connected VM TCP stream pair.
///
/// Output:
/// - Test passes when the server stream is bound to one WebSocket session and
///   duplicate binding is rejected.
///
/// Transformation:
/// - Gives production HTTP/WebSocket handoff a validated entry point instead
///   of accepting arbitrary stream handles.
#[test]
fn vm_websocket_runtime_checked_open_accepts_live_stream_and_rejects_duplicate() {
    let mut tcp = VmTcpRuntime::new();
    let (_client, server) = connected_tcp_pair_at(&mut tcp, "websocket.checked.open");
    let mut runtime = VmWebSocketRuntime::new();
    let session = runtime
        .open_session_checked(&tcp, server)
        .expect("checked open");

    assert_eq!(
        runtime.inspect_session(session).expect("inspect session"),
        VmWebSocketSessionInfo {
            stream: server,
            open: true,
            frames_sent: 0,
            frames_received: 0,
            bytes_sent: 0,
            bytes_received: 0,
        }
    );
    assert_eq!(
        runtime
            .open_session_checked(&tcp, server)
            .expect_err("duplicate stream rejected"),
        "error[vm_websocket_session]: TCP stream is already bound to a WebSocket session"
    );
    assert_eq!(runtime.session_count(), 1);
}

/// Verifies checked session open rejects invalid TCP stream state.
///
/// Inputs:
/// - One closed stream, one cancelled stream, and one fabricated unknown
///   stream handle.
///
/// Output:
/// - Test passes when each rejected open reports a stable diagnostic and no
///   WebSocket session is created.
///
/// Transformation:
/// - Prevents production WebSocket handoff from registering dead or stale TCP
///   resources.
#[test]
fn vm_websocket_runtime_checked_open_rejects_invalid_tcp_streams() {
    let mut tcp = VmTcpRuntime::new();
    let (_closed_client, closed_server) =
        connected_tcp_pair_at(&mut tcp, "websocket.checked.closed");
    let (_cancelled_client, cancelled_server) =
        connected_tcp_pair_at(&mut tcp, "websocket.checked.cancelled");
    tcp.close_stream(closed_server).expect("close stream");
    tcp.cancel_stream(cancelled_server).expect("cancel stream");
    let mut runtime = VmWebSocketRuntime::new();
    let unknown = VmTcpStream::test_handle(99_999);

    assert_eq!(
        runtime
            .open_session_checked(&tcp, closed_server)
            .expect_err("closed rejected"),
        "error[vm_websocket_session]: cannot open session for closed TCP stream"
    );
    assert_eq!(
        runtime
            .open_session_checked(&tcp, cancelled_server)
            .expect_err("cancelled rejected"),
        "error[vm_websocket_session]: cannot open session for cancelled TCP stream"
    );
    assert_eq!(
        runtime
            .open_session_checked(&tcp, unknown)
            .expect_err("unknown rejected"),
        "error[vm_websocket_tcp]: cannot open session for stream: VM TCP stream handle is unknown"
    );
    assert_eq!(runtime.session_count(), 0);
}

/// Verifies WebSocket upgrade handoff binds one live stream atomically.
///
/// Inputs:
/// - One connected VM TCP stream pair.
/// - One valid source-level WebSocket endpoint plan.
/// - RFC example `Sec-WebSocket-Key`.
///
/// Output:
/// - Test passes when the response metadata, endpoint plan, and session
///   binding are returned together.
///
/// Transformation:
/// - Proves HTTP upgrade handling can transfer ownership into the VM
///   WebSocket registry without bypassing checked stream binding.
#[test]
fn vm_websocket_runtime_accept_upgrade_binds_stream_and_endpoint() {
    let (tcp, _client, server) = connected_tcp_pair();
    let endpoint = VmWebSocketEndpointPlan::new(8, 2048).expect("endpoint plan");
    let mut runtime = VmWebSocketRuntime::new();

    let accepted = runtime
        .accept_upgrade(&tcp, server, &endpoint, "dGhlIHNhbXBsZSBub25jZQ==")
        .expect("accepted upgrade");

    assert_eq!(accepted.endpoint, endpoint);
    assert_eq!(accepted.response.status, 101);
    assert_eq!(
        accepted.response.headers,
        vec![
            ("upgrade".to_string(), "websocket".to_string()),
            ("connection".to_string(), "Upgrade".to_string()),
            (
                "sec-websocket-accept".to_string(),
                "s3pPLMBiTxaQ9kYGzzhZRbK+xOo=".to_string(),
            ),
        ]
    );
    assert_eq!(runtime.session_for_stream(server), Some(accepted.session));
    assert_eq!(
        runtime
            .inspect_session(accepted.session)
            .expect("inspect accepted session")
            .stream,
        server
    );
    assert_eq!(runtime.session_count(), 1);
}

/// Verifies malformed upgrade keys do not allocate WebSocket sessions.
///
/// Inputs:
/// - One connected VM TCP stream pair.
/// - One valid endpoint plan.
/// - Whitespace-only `Sec-WebSocket-Key`.
///
/// Output:
/// - Test passes when the stable handshake diagnostic is returned and the
///   registry remains empty.
///
/// Transformation:
/// - Keeps invalid HTTP upgrade requests from creating orphaned VM WebSocket
///   sessions.
#[test]
fn vm_websocket_runtime_accept_upgrade_rejects_blank_key_without_session() {
    let (tcp, _client, server) = connected_tcp_pair();
    let endpoint = VmWebSocketEndpointPlan::new(8, 2048).expect("endpoint plan");
    let mut runtime = VmWebSocketRuntime::new();

    assert_eq!(
        runtime
            .accept_upgrade(&tcp, server, &endpoint, "   ")
            .expect_err("blank key rejected"),
        "error[vm_websocket]: missing Sec-WebSocket-Key"
    );
    assert_eq!(runtime.session_count(), 0);
    assert_eq!(runtime.session_for_stream(server), None);
}

/// Verifies upgrade handoff rejects dead TCP stream state without allocation.
///
/// Inputs:
/// - One closed VM TCP stream and one cancelled VM TCP stream.
/// - One valid endpoint plan.
///
/// Output:
/// - Test passes when both rejected handoffs report stable diagnostics and no
///   sessions are created.
///
/// Transformation:
/// - Prevents HTTP upgrade logic from resurrecting stale VM stream resources.
#[test]
fn vm_websocket_runtime_accept_upgrade_rejects_inactive_stream_without_session() {
    let mut tcp = VmTcpRuntime::new();
    let (_closed_client, closed_server) =
        connected_tcp_pair_at(&mut tcp, "websocket.accept.closed");
    let (_cancelled_client, cancelled_server) =
        connected_tcp_pair_at(&mut tcp, "websocket.accept.cancelled");
    tcp.close_stream(closed_server).expect("close stream");
    tcp.cancel_stream(cancelled_server).expect("cancel stream");
    let endpoint = VmWebSocketEndpointPlan::new(8, 2048).expect("endpoint plan");
    let mut runtime = VmWebSocketRuntime::new();

    assert_eq!(
        runtime
            .accept_upgrade(&tcp, closed_server, &endpoint, "dGhlIHNhbXBsZSBub25jZQ==",)
            .expect_err("closed rejected"),
        "error[vm_websocket_session]: cannot open session for closed TCP stream"
    );
    assert_eq!(
        runtime
            .accept_upgrade(
                &tcp,
                cancelled_server,
                &endpoint,
                "dGhlIHNhbXBsZSBub25jZQ==",
            )
            .expect_err("cancelled rejected"),
        "error[vm_websocket_session]: cannot open session for cancelled TCP stream"
    );
    assert_eq!(runtime.session_count(), 0);
}

/// Verifies upgrade handoff rejects duplicate stream binding.
///
/// Inputs:
/// - One connected VM TCP stream pair.
/// - One endpoint plan reused across two handoff attempts.
///
/// Output:
/// - Test passes when the second handoff fails without adding another
///   session.
///
/// Transformation:
/// - Keeps WebSocket session ownership one-to-one with accepted VM TCP
///   streams.
#[test]
fn vm_websocket_runtime_accept_upgrade_rejects_duplicate_stream() {
    let (tcp, _client, server) = connected_tcp_pair();
    let endpoint = VmWebSocketEndpointPlan::new(8, 2048).expect("endpoint plan");
    let mut runtime = VmWebSocketRuntime::new();
    runtime
        .accept_upgrade(&tcp, server, &endpoint, "dGhlIHNhbXBsZSBub25jZQ==")
        .expect("first accepted upgrade");

    assert_eq!(
        runtime
            .accept_upgrade(&tcp, server, &endpoint, "dGhlIHNhbXBsZSBub25jZQ==",)
            .expect_err("duplicate rejected"),
        "error[vm_websocket_session]: TCP stream is already bound to a WebSocket session"
    );
    assert_eq!(runtime.session_count(), 1);
}
