[package]
name = "terlan-net-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
rustls = { workspace = true, features = ["ring", "std", "tls12"] }
socket2 = { version = "0.6.1", features = ["all"] }
terlan-runtime-abi = { workspace = true, features = ["poll-io"] }
mio = { version = "1.2.2", features = ["net", "os-poll"] }
url.workspace = true

[dev-dependencies]
rcgen.workspace = true
