use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};

use super::AcmeRuntimePlan;
use super::{is_acme_http01_token, unix_seconds, ACME_RENEWAL_INTERVAL};
use super::{load_certificate_chain, load_private_key};

const ACME_CERTIFICATE_CACHE_SCHEMA_VERSION: u32 = 1;
const ACME_CERTIFICATE_CACHE_FORMAT_VERSION: u32 = 1;
const ACME_CERTIFICATE_CACHE_KEY_ALGORITHM: &str = "ecdsa-p256";
const ACME_CERTIFICATE_CACHE_CHALLENGE_METHOD: &str = "http-01";
const ACME_CERTIFICATE_CACHE_ISSUING_WORKER: &str = "vm-acme-worker";
const ACME_CERTIFICATE_CACHE_MODE_LIVE: &str = "live";
const ACME_CERTIFICATE_CACHE_MODE_STAGING: &str = "staging";

/// ACME certificate cache renewal and provenance metadata.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq, Serialize)]
pub struct AcmeCertificateCacheMetadata {
    pub schema_version: u32,
    pub cache_format_version: u32,
    pub domains: Vec<String>,
    pub subject_alternative_names: Vec<String>,
    pub issuer: String,
    pub account_id: String,
    pub key_algorithm: String,
    pub challenge_method: String,
    pub acme_mode: String,
    pub not_before_unix_seconds: u64,
    pub not_after_unix_seconds: u64,
    pub issued_at_unix_seconds: u64,
    pub renew_after_unix_seconds: u64,
    pub issuing_worker_identity: String,
    pub provenance_hash: String,
}

/// Redacted ACME cache details safe for support-bundle replay.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg(test)]
pub(super) struct AcmeCacheSupportBundleRedaction {
    pub cache_dir: String,
    pub provenance_fingerprint: String,
    pub diagnostic: String,
}

/// Loads cached ACME account credentials.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
///
/// Output:
/// - `Ok(None)` when no account cache exists.
/// - `Ok(Some(AccountCredentials))` when the account cache is valid JSON.
/// - Stable `error[serve_tls]` diagnostic when the cache cannot be read or
///   decoded.
///
/// Transformation:
/// - Deserializes the opaque `instant-acme` account credential payload from
///   the deterministic project-local cache file without interpreting its
///   private fields.
pub fn load_acme_account_credentials<T: DeserializeOwned>(
    plan: &AcmeRuntimePlan,
) -> Result<Option<T>, crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    let contents = match fs::read_to_string(&plan.account_credentials_path) {
        Ok(contents) => contents,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => {
            return Err(format!(
                "error[serve_tls]: failed to read ACME account credentials `{}`: {err}",
                plan.account_credentials_path.display()
            )
            .into());
        }
    };
    Ok(serde_json::from_str::<T>(&contents)
        .map(Some)
        .map_err(|err| {
            format!(
                "error[serve_tls]: failed to parse ACME account credentials `{}`: {err}",
                plan.account_credentials_path.display()
            )
        })?)
}

/// Stores ACME account credentials.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `credentials`: opaque credentials returned by `instant-acme`.
///
/// Output:
/// - `Ok(())` when credentials are durably written to the project cache.
///
/// Transformation:
/// - Serializes through `serde_json` and writes through a temporary file before
///   renaming into place, so interrupted issuance does not leave partial
///   account JSON at the runtime path.
pub fn store_acme_account_credentials<T: Serialize>(
    plan: &AcmeRuntimePlan,
    credentials: &T,
) -> Result<(), crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    let contents = serde_json::to_string_pretty(credentials).map_err(|err| {
        format!("error[serve_tls]: failed to serialize ACME account credentials: {err}")
    })?;
    write_cache_file_atomically(&plan.account_credentials_path, contents.as_bytes())
}

/// Stores one ACME HTTP-01 challenge response.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `token`: ACME HTTP-01 challenge token.
/// - `key_authorization`: ACME key authorization body generated by
///   `instant-acme`.
///
/// Output:
/// - Path to the written challenge response file.
///
/// Transformation:
/// - Validates the token against the same URL-safe filename policy used by the
///   request handler, then writes the response under
///   `.terlan/tls/acme/http-01`.
pub fn store_acme_http01_challenge(
    plan: &AcmeRuntimePlan,
    token: &str,
    key_authorization: &str,
) -> Result<PathBuf, crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    if !is_acme_http01_token(token) {
        return Err(format!("error[serve_tls]: ACME HTTP-01 token `{token}` is invalid").into());
    }
    let path = plan.http01_challenge_dir.join(token);
    write_cache_file_atomically(&path, key_authorization.as_bytes())?;
    Ok(path)
}

/// Stores issued ACME certificate material.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `certificate_pem`: issued certificate chain PEM.
/// - `private_key_pem`: private key PEM used by the CSR.
///
/// Output:
/// - `Ok(())` when both runtime cache files are written and parseable by
///   `rustls`.
///
/// Transformation:
/// - Writes certificate/key to temporary paths, validates them through the same
///   PEM/rustls path used by serving, then atomically renames them into the
///   deterministic ACME cache.
pub fn store_acme_certificate_cache(
    plan: &AcmeRuntimePlan,
    certificate_pem: &str,
    private_key_pem: &str,
) -> Result<(), crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    let cert_temp = write_temporary_cache_file(&plan.certificate_path, certificate_pem.as_bytes())?;
    let key_temp = write_temporary_cache_file(&plan.private_key_path, private_key_pem.as_bytes())?;
    let certificates = load_certificate_chain(cert_temp.path())?;
    let private_key = load_private_key(key_temp.path())?;
    super::rustls_server_config(certificates, private_key)?;
    persist_cache_file(cert_temp, &plan.certificate_path)?;
    persist_cache_file(key_temp, &plan.private_key_path)?;
    store_acme_certificate_cache_metadata(plan, SystemTime::now())
}

/// Validates cached ACME mode provenance against the configured endpoint.
pub fn validate_acme_certificate_cache_mode(
    plan: &AcmeRuntimePlan,
    metadata: &AcmeCertificateCacheMetadata,
) -> Result<(), crate::ServiceError> {
    let expected = acme_metadata_mode(plan);
    if metadata.acme_mode == expected {
        Ok(())
    } else {
        Err(format!(
            "error[serve_tls]: ACME certificate cache metadata `{}` was issued for mode `{}` but runtime requires `{expected}`",
            plan.renewal_metadata_path.display(),
            metadata.acme_mode
        ).into())
    }
}

/// Validates the stored ACME cache provenance hash.
pub fn validate_acme_certificate_cache_provenance_hash(
    plan: &AcmeRuntimePlan,
    metadata: &AcmeCertificateCacheMetadata,
) -> Result<(), crate::ServiceError> {
    let expected = acme_cache_provenance_fingerprint(metadata);
    if metadata.provenance_hash == expected {
        Ok(())
    } else {
        Err(format!(
            "error[serve_tls]: ACME certificate cache metadata `{}` failed provenance hash validation",
            plan.renewal_metadata_path.display()
        ).into())
    }
}

/// Validates package-owned ACME cache custody before TLS startup.
pub fn validate_acme_key_custody_policy(plan: &AcmeRuntimePlan) -> Result<(), crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    validate_private_key_cache_permissions(&plan.private_key_path)
}

/// Builds ACME cache metadata safe for support bundles.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `metadata`: typed cache provenance metadata.
/// - `diagnostic`: runtime diagnostic that may contain sensitive cache data.
///
/// Output:
/// - Redacted cache directory, stable provenance fingerprint, and sanitized
///   diagnostic text.
///
/// Transformation:
/// - Keeps support bundles useful for replay while preventing account ids,
///   cache keys, or private-key PEM markers from leaving the package-owned ACME
///   cache boundary.
#[cfg(test)]
pub(super) fn redact_acme_cache_support_bundle(
    plan: &AcmeRuntimePlan,
    metadata: &AcmeCertificateCacheMetadata,
    diagnostic: &str,
) -> AcmeCacheSupportBundleRedaction {
    AcmeCacheSupportBundleRedaction {
        cache_dir: plan.cache_dir.display().to_string(),
        provenance_fingerprint: acme_cache_provenance_fingerprint(metadata),
        diagnostic: redact_acme_cache_support_bundle_diagnostic(metadata, diagnostic),
    }
}

/// Restricts a private key cache file to owner-only access where supported.
pub fn restrict_private_key_file_permissions(path: &Path) -> Result<(), crate::ServiceError> {
    restrict_private_key_file_permissions_impl(path)
}

#[cfg(unix)]
fn restrict_private_key_file_permissions_impl(path: &Path) -> Result<(), crate::ServiceError> {
    let mut permissions = fs::metadata(path)
        .map_err(|err| {
            format!(
                "error[serve_tls]: failed to inspect ACME private key cache `{}`: {err}",
                path.display()
            )
        })?
        .permissions();
    permissions.set_mode(0o600);
    Ok(fs::set_permissions(path, permissions).map_err(|err| {
        format!(
            "error[serve_tls]: failed to restrict ACME private key cache `{}`: {err}",
            path.display()
        )
    })?)
}

#[cfg(not(unix))]
fn restrict_private_key_file_permissions_impl(_path: &Path) -> Result<(), crate::ServiceError> {
    Ok(())
}

/// Validates a private key cache file is not group/world accessible.
pub fn validate_private_key_cache_permissions(path: &Path) -> Result<(), crate::ServiceError> {
    validate_private_key_cache_permissions_impl(path)
}

#[cfg(unix)]
fn validate_private_key_cache_permissions_impl(path: &Path) -> Result<(), crate::ServiceError> {
    let mode = fs::metadata(path)
        .map_err(|err| {
            format!(
                "error[serve_tls]: failed to inspect ACME private key cache `{}`: {err}",
                path.display()
            )
        })?
        .permissions()
        .mode()
        & 0o777;
    if mode & 0o077 == 0 {
        Ok(())
    } else {
        Err(format!(
            "error[serve_tls]: ACME private key cache `{}` must not be group/world accessible; mode {:03o}",
            path.display(),
            mode
        ).into())
    }
}

#[cfg(not(unix))]
fn validate_private_key_cache_permissions_impl(_path: &Path) -> Result<(), crate::ServiceError> {
    Ok(())
}

/// Loads ACME certificate cache renewal metadata.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
///
/// Output:
/// - Parsed renewal metadata.
/// - Stable diagnostics for missing or malformed metadata.
///
/// Transformation:
/// - Keeps auto TLS cache age validation tied to a deterministic JSON file
///   beside the issued certificate material.
pub fn load_acme_certificate_cache_metadata(
    plan: &AcmeRuntimePlan,
) -> Result<AcmeCertificateCacheMetadata, crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    let contents = fs::read_to_string(&plan.renewal_metadata_path).map_err(|err| {
        format!(
            "error[serve_tls]: failed to read ACME certificate cache metadata `{}`: {err}",
            plan.renewal_metadata_path.display()
        )
    })?;
    Ok(serde_json::from_str(&contents).map_err(|err| {
        format!(
            "error[serve_tls]: failed to parse ACME certificate cache metadata `{}`: {err}",
            plan.renewal_metadata_path.display()
        )
    })?)
}

/// Stores ACME certificate cache renewal metadata.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `issued_at`: issuance time recorded by the runtime.
///
/// Output:
/// - `Ok(())` when renewal metadata is durably written.
///
/// Transformation:
/// - Writes JSON through the same atomic cache-file path as certificate
///   material so runtime cache loading can fail closed when metadata is stale
///   or missing.
pub fn store_acme_certificate_cache_metadata(
    plan: &AcmeRuntimePlan,
    issued_at: SystemTime,
) -> Result<(), crate::ServiceError> {
    validate_acme_cache_paths(plan)?;
    let issued_at_unix_seconds = unix_seconds(issued_at)?;
    let mut metadata = AcmeCertificateCacheMetadata {
        schema_version: ACME_CERTIFICATE_CACHE_SCHEMA_VERSION,
        cache_format_version: ACME_CERTIFICATE_CACHE_FORMAT_VERSION,
        domains: plan.domains.clone(),
        subject_alternative_names: plan.domains.clone(),
        issuer: acme_metadata_issuer(plan).to_string(),
        account_id: acme_metadata_account_id(plan).to_string(),
        key_algorithm: ACME_CERTIFICATE_CACHE_KEY_ALGORITHM.to_string(),
        challenge_method: ACME_CERTIFICATE_CACHE_CHALLENGE_METHOD.to_string(),
        acme_mode: acme_metadata_mode(plan).to_string(),
        not_before_unix_seconds: issued_at_unix_seconds,
        not_after_unix_seconds: issued_at_unix_seconds + ACME_RENEWAL_INTERVAL.as_secs(),
        issued_at_unix_seconds,
        renew_after_unix_seconds: issued_at_unix_seconds + ACME_RENEWAL_INTERVAL.as_secs(),
        issuing_worker_identity: ACME_CERTIFICATE_CACHE_ISSUING_WORKER.to_string(),
        provenance_hash: String::new(),
    };
    metadata.provenance_hash = acme_cache_provenance_fingerprint(&metadata);
    let contents = serde_json::to_vec_pretty(&metadata).map_err(|err| {
        format!("error[serve_tls]: failed to serialize ACME certificate cache metadata: {err}")
    })?;
    write_cache_file_atomically(&plan.renewal_metadata_path, &contents)
}

fn acme_metadata_issuer(plan: &AcmeRuntimePlan) -> &'static str {
    match plan.primary_provider {
        super::ProjectServerTlsProvider::LetsEncrypt => "letsencrypt",
        super::ProjectServerTlsProvider::ZeroSsl => "zerossl",
    }
}

fn acme_metadata_account_id(plan: &AcmeRuntimePlan) -> &str {
    plan.email
        .as_deref()
        .map(str::trim)
        .filter(|email| !email.is_empty())
        .unwrap_or("acme-account")
}

fn acme_metadata_mode(plan: &AcmeRuntimePlan) -> &'static str {
    if plan.directory_url.contains("staging") {
        ACME_CERTIFICATE_CACHE_MODE_STAGING
    } else {
        ACME_CERTIFICATE_CACHE_MODE_LIVE
    }
}

#[cfg(test)]
fn redact_acme_cache_support_bundle_diagnostic(
    metadata: &AcmeCertificateCacheMetadata,
    diagnostic: &str,
) -> String {
    if contains_private_key_material(diagnostic) {
        return "<redacted acme private key material>".to_string();
    }
    diagnostic
        .replace(&metadata.account_id, "<redacted-acme-account>")
        .replace(&metadata.issuing_worker_identity, "<redacted-acme-worker>")
}

#[cfg(test)]
fn contains_private_key_material(text: &str) -> bool {
    [
        "-----BEGIN PRIVATE KEY-----",
        "-----BEGIN RSA PRIVATE KEY-----",
        "-----BEGIN EC PRIVATE KEY-----",
    ]
    .iter()
    .any(|marker| text.contains(marker))
}

pub(crate) fn validate_acme_cache_paths(plan: &AcmeRuntimePlan) -> Result<(), crate::ServiceError> {
    for (label, path) in [
        ("certificate", &plan.certificate_path),
        ("private key", &plan.private_key_path),
        ("renewal metadata", &plan.renewal_metadata_path),
        ("account credentials", &plan.account_credentials_path),
        ("HTTP-01", &plan.http01_challenge_dir),
    ] {
        validate_acme_cache_path(label, &plan.cache_dir, path)?;
    }
    Ok(())
}

/// Rejects lexical traversal and existing symlink escapes. This is not a
/// race-free directory capability: the project cache must remain host-controlled.
pub(crate) fn validate_acme_cache_path(
    label: &str,
    cache_dir: &Path,
    path: &Path,
) -> Result<(), crate::ServiceError> {
    let escaped = || {
        format!(
        "error[serve_tls]: ACME {label} cache path `{}` escapes package-owned cache directory `{}`",
        path.display(), cache_dir.display()
    )
    };
    let relative = path.strip_prefix(cache_dir).map_err(|_| escaped())?;
    if relative.as_os_str().is_empty()
        || relative
            .components()
            .any(|part| !matches!(part, std::path::Component::Normal(_)))
    {
        return Err(escaped().into());
    }
    if cache_dir.exists() {
        let root = fs::canonicalize(cache_dir).map_err(|err| {
            format!(
                "error[serve_tls]: failed to resolve ACME cache directory `{}`: {err}",
                cache_dir.display()
            )
        })?;
        for ancestor in path.ancestors() {
            match fs::symlink_metadata(ancestor) {
                Ok(_) => {
                    let resolved = fs::canonicalize(ancestor).map_err(|err| format!(
                        "error[serve_tls]: failed to resolve ACME {label} cache path `{}`: {err}", ancestor.display()
                    ))?;
                    if !resolved.starts_with(&root) {
                        return Err(escaped().into());
                    }
                    break;
                }
                Err(err) if err.kind() == std::io::ErrorKind::NotFound => continue,
                Err(err) => {
                    return Err(format!(
                        "error[serve_tls]: failed to inspect ACME {label} cache path `{}`: {err}",
                        ancestor.display()
                    )
                    .into())
                }
            }
        }
    }
    Ok(())
}

fn acme_cache_provenance_fingerprint(metadata: &AcmeCertificateCacheMetadata) -> String {
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for field in acme_cache_provenance_fields(metadata) {
        for byte in field.as_bytes() {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
        hash ^= 0xff;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

fn acme_cache_provenance_fields(metadata: &AcmeCertificateCacheMetadata) -> Vec<String> {
    vec![
        metadata.schema_version.to_string(),
        metadata.cache_format_version.to_string(),
        metadata.domains.join(","),
        metadata.subject_alternative_names.join(","),
        metadata.issuer.clone(),
        metadata.account_id.clone(),
        metadata.key_algorithm.clone(),
        metadata.challenge_method.clone(),
        metadata.acme_mode.clone(),
        metadata.not_before_unix_seconds.to_string(),
        metadata.not_after_unix_seconds.to_string(),
        metadata.issued_at_unix_seconds.to_string(),
        metadata.renew_after_unix_seconds.to_string(),
        metadata.issuing_worker_identity.clone(),
    ]
}

/// Creates a private, unique sibling temporary file through maintained tempfile.
fn write_temporary_cache_file(
    path: &Path,
    contents: &[u8],
) -> Result<tempfile::NamedTempFile, crate::ServiceError> {
    use std::io::Write;
    let parent = path.parent().ok_or_else(|| {
        format!(
            "error[serve_tls]: ACME cache path `{}` has no parent",
            path.display()
        )
    })?;
    fs::create_dir_all(parent).map_err(|err| {
        format!(
            "error[serve_tls]: failed to create ACME cache directory `{}`: {err}",
            parent.display()
        )
    })?;
    let mut file = tempfile::NamedTempFile::new_in(parent).map_err(|err| {
        format!(
            "error[serve_tls]: failed to create temporary ACME cache file in `{}`: {err}",
            parent.display()
        )
    })?;
    file.write_all(contents)
        .and_then(|()| file.as_file().sync_all())
        .map_err(|err| {
            format!(
                "error[serve_tls]: failed to write ACME cache file `{}`: {err}",
                path.display()
            )
        })?;
    Ok(file)
}

/// Publishes one complete file; failed writes/persistence discard the temporary file.
fn persist_cache_file(
    file: tempfile::NamedTempFile,
    path: &Path,
) -> Result<(), crate::ServiceError> {
    Ok(file.persist(path).map(|_| ()).map_err(|err| {
        format!(
            "error[serve_tls]: failed to move ACME cache file to `{}`: {err}",
            path.display()
        )
    })?)
}

fn write_cache_file_atomically(path: &Path, contents: &[u8]) -> Result<(), crate::ServiceError> {
    persist_cache_file(write_temporary_cache_file(path, contents)?, path)
}
