use super::*;
use crate::postgres;
use crate::resource::ResourceError;

/// Extracts a handle from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain a handle.
///
/// Output:
/// - `Some(handle)` when the reply is a handle success.
/// - `None` after asserting the reply had an unexpected shape.
///
/// Transformation:
/// - Pattern-matches the stable reply term without unwrap/expect.
fn handle_reply(reply: SafeNativeReplyTerm) -> Option<SafeNativeHandle> {
    let SafeNativeReplyTerm::Ok(SafeNativeTerm::Handle { id, generation }) = reply else {
        return None;
    };
    Some(SafeNativeHandle { id, generation })
}

/// Builds a handle term from a runtime handle.
///
/// Inputs:
/// - `handle`: opaque runtime handle.
///
/// Output:
/// - Stable term that carries the handle id and generation.
///
/// Transformation:
/// - Copies handle identity into the term shape expected by runtime calls.
fn handle_term(handle: SafeNativeHandle) -> SafeNativeTerm {
    SafeNativeTerm::Handle {
        id: handle.id,
        generation: handle.generation,
    }
}

/// Extracts a text value from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain text.
///
/// Output:
/// - `Some(text)` when the reply is a text success.
/// - `None` for any other reply shape.
///
/// Transformation:
/// - Pattern-matches the stable reply term without panicking.
fn text_reply(reply: SafeNativeReplyTerm) -> Option<String> {
    let SafeNativeReplyTerm::Ok(SafeNativeTerm::Text(value)) = reply else {
        return None;
    };
    Some(value)
}

/// Extracts an optional handle from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain an optional handle.
///
/// Output:
/// - `Some(handle)` when the reply is `OptionalHandle(Some(_))`.
/// - `None` for missing rows or unexpected reply shapes.
///
/// Transformation:
/// - Uses the same term shape generated by resource-backed optional results.
fn some_handle_reply(reply: SafeNativeReplyTerm) -> Option<SafeNativeHandle> {
    let SafeNativeReplyTerm::Ok(SafeNativeTerm::OptionalHandle(Some(handle))) = reply else {
        return None;
    };
    Some(handle)
}

/// Reads the optional live Postgres test URL.
///
/// Inputs:
/// - `test_name`: name used in the skip diagnostic.
///
/// Output:
/// - `Some(url)` when `TERLAN_TEST_POSTGRES_URL` is configured.
/// - `None` when the live handler test should be skipped.
///
/// Transformation:
/// - Reads only the process environment and emits a skip line for ordinary
///   unit test runs without a database.
fn live_postgres_url(test_name: &str) -> Option<String> {
    match std::env::var("TERLAN_TEST_POSTGRES_URL") {
        Ok(url) => Some(url),
        Err(_) => {
            eprintln!("skipping {test_name}; TERLAN_TEST_POSTGRES_URL is not set");
            None
        }
    }
}

/// Verifies JSON can execute through the term runtime path.
///
/// Inputs:
/// - JSON text, object key, and operation ids.
///
/// Output:
/// - Test passes when parse/get/as-string returns the expected text.
///
/// Transformation:
/// - Exercises term decoding, resource-backed dispatch, opaque handle
///   storage, and reply encoding together.
#[test]
fn runtime_executes_json_operations_through_terms() {
    let mut runtime = SafeNativeRuntime::new();
    let Some(root) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[SafeNativeTerm::Text(String::from(r#"{"name":"Ada"}"#))],
    )) else {
        return;
    };
    let Some(name) = handle_reply(runtime.call(
        "std.data.json.get",
        &[
            SafeNativeTerm::Handle {
                id: root.id,
                generation: root.generation,
            },
            SafeNativeTerm::Text(String::from("name")),
        ],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.data.json.as_string",
            &[SafeNativeTerm::Handle {
                id: name.id,
                generation: name.generation,
            }],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Text(String::from("Ada")))
    );
}

/// Verifies Base64 can execute through the term runtime path.
///
/// Inputs:
/// - Text operation argument.
///
/// Output:
/// - Test passes when encode returns the expected Base64 text.
///
/// Transformation:
/// - Exercises primitive-only SafeNative dispatch without resource handles.
#[test]
fn runtime_executes_base64_operations_through_terms() {
    let mut runtime = SafeNativeRuntime::new();

    assert_eq!(
        runtime.call(
            "std.encoding.base64.encode",
            &[SafeNativeTerm::Text(String::from("hello"))],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Text(String::from("aGVsbG8=")))
    );
}

/// Verifies path operations can return optional handle terms.
///
/// Inputs:
/// - Path text with a parent component.
///
/// Output:
/// - Test passes when parent returns `OptionalHandle(Some(_))`.
///
/// Transformation:
/// - Exercises optional opaque resource results through the runtime term
///   boundary.
#[test]
fn runtime_executes_path_optional_handle_operations_through_terms() {
    let mut runtime = SafeNativeRuntime::new();
    let Some(path) = handle_reply(runtime.call(
        "std.io.path.from_string",
        &[SafeNativeTerm::Text(String::from("src/main.terl"))],
    )) else {
        return;
    };

    let parent = runtime.call(
        "std.io.path.parent",
        &[SafeNativeTerm::Handle {
            id: path.id,
            generation: path.generation,
        }],
    );

    assert!(matches!(
        parent,
        SafeNativeReplyTerm::Ok(SafeNativeTerm::OptionalHandle(Some(_)))
    ));
}

/// Verifies HTTP cookie jars execute through the term runtime path.
///
/// Inputs:
/// - A server-owned request resource with one parsed incoming cookie.
///
/// Output:
/// - Test passes when the runtime creates a cookie jar handle, reads an
///   incoming cookie, and records cookie set/delete mutations as `Unit`
///   operations.
///
/// Transformation:
/// - Exercises the bridge path a server adapter will use: register request
///   state, call `Request.cookies`, then mutate the returned jar by handle.
#[test]
fn runtime_executes_http_cookie_jar_operations_through_terms() {
    let mut runtime = SafeNativeRuntime::new();
    let request = http::Request::from_parts_with_metadata(
        "GET",
        "/profile",
        "",
        Vec::new(),
        Vec::new(),
        vec![("theme".to_string(), "dark".to_string())],
    );
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };
    let Some(jar) = handle_reply(runtime.call(
        "std.http.request.cookies",
        &[SafeNativeTerm::Handle {
            id: request.id,
            generation: request.generation,
        }],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.http.cookies.get",
            &[
                SafeNativeTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                SafeNativeTerm::Text(String::from("theme")),
            ],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::OptionalText(Some(String::from("dark"))))
    );
    assert_eq!(
        runtime.call(
            "std.http.cookies.set",
            &[
                SafeNativeTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                SafeNativeTerm::Text(String::from("session")),
                SafeNativeTerm::Text(String::from("abc123")),
                SafeNativeTerm::Text(String::from("/")),
                SafeNativeTerm::Bool(true),
                SafeNativeTerm::Bool(false),
            ],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Unit)
    );
    assert_eq!(
        runtime.call(
            "std.http.cookies.delete",
            &[
                SafeNativeTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                SafeNativeTerm::Text(String::from("theme")),
                SafeNativeTerm::Text(String::from("/")),
            ],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Unit)
    );
    assert_eq!(
        runtime.http_cookie_mutations(jar),
        Ok(vec![
            String::from("session=abc123; HttpOnly; Path=/"),
            String::from("theme=; Path=/; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT")
        ])
    );
}

/// Verifies HTTP response resources can be returned to a server adapter.
///
/// Inputs:
/// - Response text and status supplied through stable runtime terms.
///
/// Output:
/// - Test passes when `std.http.response.text` returns a handle that can be
///   read back as a portable HTTP response snapshot.
///
/// Transformation:
/// - Exercises the last step of handler execution without requiring any live
///   database state.
#[test]
fn runtime_returns_http_response_resources_through_terms() {
    let mut runtime = SafeNativeRuntime::new();
    let Some(response) = handle_reply(runtime.call(
        "std.http.response.text",
        &[
            SafeNativeTerm::Text(String::from("ok")),
            SafeNativeTerm::Int(202),
        ],
    )) else {
        return;
    };
    let Some(response) = runtime.http_response(response).ok() else {
        return;
    };

    assert_eq!(response.status_code(), 202);
    assert_eq!(response.content_type(), "text/plain; charset=utf-8");
    assert_eq!(response.body(), "ok");
}

/// Verifies response extraction rejects non-response resource handles.
///
/// Inputs:
/// - A request handle registered in the runtime.
///
/// Output:
/// - Test passes when extracting it as a response returns `resource.kind`.
///
/// Transformation:
/// - Exercises the server-side response handle validation failure path.
#[test]
fn runtime_rejects_non_response_handles_as_handler_results() {
    let mut runtime = SafeNativeRuntime::new();
    let request = http::Request::from_parts("GET", "/", "");
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };
    let error = runtime
        .http_response(request)
        .err()
        .unwrap_or_else(|| ResourceError::new("missing", "missing"));

    assert_eq!(error.code(), "resource.kind");
}

/// Verifies an HTTP handler-shaped runtime flow can call Postgres and respond.
///
/// Inputs:
/// - `TERLAN_TEST_POSTGRES_URL`: optional live Postgres URL supplied by an
///   opt-in integration gate.
///
/// Output:
/// - Test is skipped when no URL is configured.
/// - Test passes when one runtime owns request state, a live Postgres pool,
///   the queried row, and the final HTTP response resource.
///
/// Transformation:
/// - Simulates the server bridge sequence for a Terlan HTTP handler: register
///   the request, read request data through `std.http.request.*`, connect and
///   query through `std.db.postgres.*`, then return `std.http.response.text`.
#[test]
fn runtime_executes_full_cycle_http_postgres_handler_when_configured() {
    let Some(url) = live_postgres_url("live HTTP handler Postgres runtime test") else {
        return;
    };
    let mut runtime = SafeNativeRuntime::new();
    let request = http::Request::from_parts_with_metadata(
        "GET",
        "/db-health",
        "",
        Vec::new(),
        vec![(String::from("check"), String::from("postgres"))],
        Vec::new(),
    );
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };

    let Some(path) = text_reply(runtime.call("std.http.request.path", &[handle_term(request)]))
    else {
        return;
    };
    assert_eq!(path, "/db-health");

    let Some(path_json) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[SafeNativeTerm::Text(String::from("\"/db-health\""))],
    )) else {
        return;
    };
    let config = postgres::Config::new(url)
        .with_pool_limits(1, 2)
        .with_timeouts(1_000, 1_000);
    let Some(pool) = handle_reply(runtime.call(
        "std.db.postgres.connect",
        &[SafeNativeTerm::PostgresConfig(config)],
    )) else {
        return;
    };
    let Some(row) = some_handle_reply(runtime.call(
        "std.db.postgres.query_one",
        &[
            handle_term(pool),
            SafeNativeTerm::Text(String::from(
                "SELECT $1::TEXT AS request_path, 'postgres-ok'::TEXT AS status",
            )),
            SafeNativeTerm::List(vec![handle_term(path_json)]),
        ],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.db.postgres.string",
            &[
                handle_term(row),
                SafeNativeTerm::Text(String::from("request_path"))
            ],
        ),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Text(String::from("/db-health")))
    );
    let Some(status) = text_reply(runtime.call(
        "std.db.postgres.string",
        &[
            handle_term(row),
            SafeNativeTerm::Text(String::from("status")),
        ],
    )) else {
        return;
    };
    let Some(response) = handle_reply(runtime.call(
        "std.http.response.text",
        &[
            SafeNativeTerm::Text(format!("{path}:{status}")),
            SafeNativeTerm::Int(200),
        ],
    )) else {
        return;
    };
    let Some(response) = runtime.http_response(response).ok() else {
        return;
    };

    assert_eq!(response.status_code(), 200);
    assert_eq!(response.content_type(), "text/plain; charset=utf-8");
    assert_eq!(response.body(), "/db-health:postgres-ok");
}

/// Verifies disposed handles are rejected by later runtime calls.
///
/// Inputs:
/// - JSON parse output handle disposed before a second call.
///
/// Output:
/// - Test passes when the later operation returns `resource.stale_handle`.
///
/// Transformation:
/// - Exercises deterministic cleanup and stale-handle rejection through the
///   term runtime boundary.
#[test]
fn runtime_rejects_disposed_handles_through_terms() {
    let mut runtime = SafeNativeRuntime::new();
    let Some(root) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[SafeNativeTerm::Text(String::from("null"))],
    )) else {
        return;
    };
    assert_eq!(
        runtime.dispose(root),
        SafeNativeReplyTerm::Ok(SafeNativeTerm::Unit)
    );

    assert_eq!(
        runtime.call(
            "std.data.json.is_null",
            &[SafeNativeTerm::Handle {
                id: root.id,
                generation: root.generation,
            }],
        ),
        SafeNativeReplyTerm::Error {
            code: String::from("resource.stale_handle"),
            message: String::from("SafeNative resource handle 1 generation 1 is not live."),
            offset: 0,
        }
    );
}
