use terlan_typeck::{
    CoreExpr, CoreFunction, CoreIntrinsicCall, CoreIntrinsicId, CoreModule, CorePattern,
    CorePrimitiveIntrinsic, CoreType,
};

/// Emits a narrow Rust/native probe artifact from CoreIR.
///
/// Inputs:
/// - `module`: backend-independent CoreIR module produced by the formal
///   compiler pipeline.
///
/// Output:
/// - Rust source text for functions currently supported by the native
///   neutrality probe.
///
/// Transformation:
/// - Converts CoreIR function signatures and a selected expression subset into
///   plain Rust functions, preserving public/private visibility while rejecting
///   unsupported bodies into explicit `unimplemented!()` stubs.
pub(crate) fn emit_core_module_to_rust(module: &CoreModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Terlan Rust/native neutrality probe.\n");
    out.push_str("// This is not a release backend artifact.\n\n");

    for function in &module.functions {
        out.push_str(&emit_core_function_to_rust(function));
        out.push('\n');
    }

    out
}

/// Emits one CoreIR function as Rust source.
///
/// Inputs:
/// - `function`: CoreIR function signature and clause set.
///
/// Output:
/// - Rust function declaration text.
///
/// Transformation:
/// - Maps CoreIR visibility, parameter types, return type, and supported
///   single-clause bodies into Rust syntax; unsupported bodies stay explicit
///   stubs so the probe remains compilable without inventing semantics.
fn emit_core_function_to_rust(function: &CoreFunction) -> String {
    let visibility = if function.public { "pub " } else { "" };
    let params = function
        .params
        .iter()
        .map(|param| {
            format!(
                "{}: {}",
                rust_identifier(&param.name),
                core_type_to_rust(param.core_ty.as_ref(), &param.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let return_type = core_type_to_rust(function.core_return_type.as_ref(), &function.return_type);
    let body = emit_core_function_body_to_rust(function).unwrap_or_else(|| {
        "    unimplemented!(\"unsupported Terlan Rust probe body\")\n".to_string()
    });

    format!(
        "{visibility}fn {}({params}) -> {return_type} {{\n{body}}}\n",
        rust_identifier(&function.name)
    )
}

/// Lowers one CoreIR function body into Rust when it is in the supported subset.
///
/// Inputs:
/// - `function`: CoreIR function whose clause body may be emitted.
///
/// Output:
/// - Rust function body text for supported single-clause functions.
/// - `None` for unsupported clauses, guards, patterns, or expressions.
///
/// Transformation:
/// - Accepts one unguarded clause with direct variable patterns matching the
///   declared parameters, then emits the CoreIR expression as the function's
///   final Rust expression.
fn emit_core_function_body_to_rust(function: &CoreFunction) -> Option<String> {
    let [clause] = function.clauses.as_slice() else {
        return None;
    };
    if clause.guard.is_some() {
        return None;
    }
    if !core_clause_patterns_match_function_params(function, &clause.core_patterns) {
        return None;
    }
    Some(format!(
        "    {}\n",
        core_expr_to_rust(clause.body.core_expr.as_ref()?)?
    ))
}

/// Checks whether CoreIR clause patterns are direct parameter bindings.
///
/// Inputs:
/// - `function`: function whose parameter list defines the Rust callable
///   surface.
/// - `patterns`: CoreIR clause parameter patterns.
///
/// Output:
/// - `true` when every pattern is the same variable as its corresponding
///   parameter.
///
/// Transformation:
/// - Rejects destructuring and literal-pattern dispatch so the first native
///   probe slice does not choose Rust pattern lowering semantics prematurely.
fn core_clause_patterns_match_function_params(
    function: &CoreFunction,
    patterns: &[Option<CorePattern>],
) -> bool {
    function.params.len() == patterns.len()
        && function
            .params
            .iter()
            .zip(patterns.iter())
            .all(|(param, pattern)| {
                matches!(pattern, Some(CorePattern::Var(name)) if name == &param.name)
                    && is_rust_identifier(&param.name)
            })
}

/// Lowers a supported CoreIR expression into Rust expression text.
///
/// Inputs:
/// - `expr`: typed CoreIR expression.
///
/// Output:
/// - Rust expression text for the current native probe subset.
/// - `None` for CoreIR forms that still need target semantics.
///
/// Transformation:
/// - Recursively emits portable scalar values, local calls, callable-value
///   calls, pipe-forward calls, unary negation, and selected binary operators
///   without reading source syntax or backend-specific metadata.
fn core_expr_to_rust(expr: &CoreExpr) -> Option<String> {
    match expr {
        CoreExpr::Int(value) => Some(value.to_string()),
        CoreExpr::Float(value) => rust_float_literal(value),
        CoreExpr::Atom(value) | CoreExpr::Var(value) if value == "true" || value == "false" => {
            Some(value.clone())
        }
        CoreExpr::Binary(value) | CoreExpr::Atom(value) => Some(rust_string_expr(value)),
        CoreExpr::Var(name) if is_rust_identifier(name) => Some(rust_identifier(name)),
        CoreExpr::Call { function, args } => core_call_expr_to_rust(function, args),
        CoreExpr::FunctionCall { callee, args } => core_function_call_expr_to_rust(callee, args),
        CoreExpr::Intrinsic(call) => core_intrinsic_call_expr_to_rust(call),
        CoreExpr::UnaryOp { operator, operand } if operator == "-" => {
            Some(format!("(-{})", core_expr_to_rust(operand)?))
        }
        CoreExpr::BinaryOp {
            operator,
            left,
            right,
        } => {
            if operator == "|>" {
                return core_pipe_forward_expr_to_rust(left, right);
            }
            if operator == "div" {
                return Some(format!(
                    "({} / {})",
                    core_expr_to_rust(left)?,
                    core_expr_to_rust(right)?
                ));
            }
            let operator = rust_binary_operator(operator)?;
            Some(format!(
                "({} {} {})",
                core_expr_to_rust(left)?,
                operator,
                core_expr_to_rust(right)?
            ))
        }
        _ => None,
    }
}

/// Lowers a supported CoreIR intrinsic call into Rust expression text.
///
/// Inputs:
/// - `call`: CoreIR intrinsic call with a closed backend-neutral intrinsic id.
///
/// Output:
/// - Rust expression text for the supported intrinsic subset.
/// - `None` when the intrinsic has no selected Rust/native probe lowering yet.
///
/// Transformation:
/// - Maps compiler-owned primitive intrinsic ids to Rust standard-library
///   operations without exposing Rust names back into CoreIR or source syntax.
fn core_intrinsic_call_expr_to_rust(call: &CoreIntrinsicCall) -> Option<String> {
    match &call.id {
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringContains) => {
            let [value, pattern] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "{}.contains({}.as_str())",
                core_expr_to_rust(value)?,
                core_expr_to_rust(pattern)?
            ))
        }
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringStartsWith) => {
            let [value, prefix] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "{}.starts_with({}.as_str())",
                core_expr_to_rust(value)?,
                core_expr_to_rust(prefix)?
            ))
        }
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringLength) => {
            let [value] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "({}.chars().count() as i64)",
                core_expr_to_rust(value)?
            ))
        }
        _ => None,
    }
}

/// Lowers a local named CoreIR call into Rust expression text.
///
/// Inputs:
/// - `function`: local CoreIR function name.
/// - `args`: CoreIR argument expressions.
///
/// Output:
/// - Rust call expression text, or `None` for unsupported names/arguments.
///
/// Transformation:
/// - Emits `function(arg1, arg2, ...)` with sanitized Rust identifiers.
fn core_call_expr_to_rust(function: &str, args: &[CoreExpr]) -> Option<String> {
    if !is_rust_identifier(function) {
        return None;
    }
    let args = args
        .iter()
        .map(core_expr_to_rust)
        .collect::<Option<Vec<_>>>()?
        .join(", ");
    Some(format!("{}({args})", rust_identifier(function)))
}

/// Lowers a CoreIR function-value invocation into Rust expression text.
///
/// Inputs:
/// - `callee`: CoreIR expression that should evaluate to a callable value.
/// - `args`: CoreIR argument expressions.
///
/// Output:
/// - Rust call expression text, or `None` for unsupported callees/arguments.
///
/// Transformation:
/// - Emits `(callee)(args...)`, preserving Terlan's `f.(args)` distinction from
///   named calls without selecting a closure runtime beyond Rust's callable
///   expression syntax.
fn core_function_call_expr_to_rust(callee: &CoreExpr, args: &[CoreExpr]) -> Option<String> {
    let callee = core_expr_to_rust(callee)?;
    let args = args
        .iter()
        .map(core_expr_to_rust)
        .collect::<Option<Vec<_>>>()?
        .join(", ");
    Some(format!("({callee})({args})"))
}

/// Lowers a focused CoreIR pipe-forward expression into Rust call syntax.
///
/// Inputs:
/// - `left`: piped CoreIR value.
/// - `right`: CoreIR call expression receiving the piped value.
///
/// Output:
/// - Rust call expression text for supported pipe targets.
/// - `None` when the right side is not a named or function-value call.
///
/// Transformation:
/// - Converts `value |> f(extra)` into `f(value, extra)` and `value |> f.(extra)`
///   into `(f)(value, extra)`.
fn core_pipe_forward_expr_to_rust(left: &CoreExpr, right: &CoreExpr) -> Option<String> {
    match right {
        CoreExpr::Call { function, args } => {
            if !is_rust_identifier(function) {
                return None;
            }
            let mut emitted_args = vec![core_expr_to_rust(left)?];
            emitted_args.extend(
                args.iter()
                    .map(core_expr_to_rust)
                    .collect::<Option<Vec<_>>>()?,
            );
            Some(format!(
                "{}({})",
                rust_identifier(function),
                emitted_args.join(", ")
            ))
        }
        CoreExpr::FunctionCall { callee, args } => {
            let callee = core_expr_to_rust(callee)?;
            let mut emitted_args = vec![core_expr_to_rust(left)?];
            emitted_args.extend(
                args.iter()
                    .map(core_expr_to_rust)
                    .collect::<Option<Vec<_>>>()?,
            );
            Some(format!("({callee})({})", emitted_args.join(", ")))
        }
        _ => None,
    }
}

/// Maps a CoreIR type into the Rust probe type surface.
///
/// Inputs:
/// - `core_type`: structured CoreIR type, when available.
/// - `fallback`: source-level type text for functions that do not yet carry a
///   structured type payload.
///
/// Output:
/// - Rust type text accepted by the native probe.
///
/// Transformation:
/// - Prefers structured CoreIR types and falls back to source type names,
///   mapping unknown terms to `()` so unsupported shapes remain explicit
///   compile-time placeholders rather than backend-specific runtime values.
fn core_type_to_rust(core_type: Option<&CoreType>, fallback: &str) -> String {
    match core_type {
        Some(CoreType::Int) => "i64".to_string(),
        Some(CoreType::Float) | Some(CoreType::Number) => "f64".to_string(),
        Some(CoreType::Bool) => "bool".to_string(),
        Some(CoreType::String) | Some(CoreType::Binary) => "String".to_string(),
        Some(CoreType::Never) => "!".to_string(),
        Some(CoreType::Arrow {
            params,
            return_type,
        }) => format!(
            "fn({}) -> {}",
            params
                .iter()
                .map(|param| core_type_to_rust(Some(param), "Term"))
                .collect::<Vec<_>>()
                .join(", "),
            core_type_to_rust(Some(return_type), "Term")
        ),
        Some(CoreType::Term) | Some(CoreType::Dynamic) | None => match fallback {
            "Int" => "i64".to_string(),
            "Float" | "Number" => "f64".to_string(),
            "Bool" => "bool".to_string(),
            "String" | "Binary" | "Text" => "String".to_string(),
            "Never" => "!".to_string(),
            _ => "()".to_string(),
        },
        _ => "()".to_string(),
    }
}

/// Maps a CoreIR binary operator into Rust.
///
/// Inputs:
/// - `operator`: normalized CoreIR binary operator token.
///
/// Output:
/// - Rust operator token for the supported subset.
/// - `None` for operators requiring target-specific semantics.
///
/// Transformation:
/// - Keeps arithmetic and comparison operators textual while preserving the
///   Terlan `==` / `!=` equality surface.
fn rust_binary_operator(operator: &str) -> Option<&'static str> {
    match operator {
        "+" => Some("+"),
        "-" => Some("-"),
        "*" => Some("*"),
        "/" => Some("/"),
        "==" => Some("=="),
        "!=" => Some("!="),
        ">" => Some(">"),
        ">=" => Some(">="),
        "<" => Some("<"),
        "<=" => Some("<="),
        "and" | "&&" => Some("&&"),
        "or" | "||" => Some("||"),
        _ => None,
    }
}

/// Converts a CoreIR float payload into a Rust float literal.
///
/// Inputs:
/// - `value`: CoreIR float payload text.
///
/// Output:
/// - Rust finite float literal text.
/// - `None` for non-finite or unparsable payloads.
///
/// Transformation:
/// - Parses through `f64` to reject non-portable float payloads before native
///   probe emission.
fn rust_float_literal(value: &str) -> Option<String> {
    let parsed = value.parse::<f64>().ok()?;
    parsed.is_finite().then(|| value.to_string())
}

/// Converts a CoreIR string-like payload into a Rust `String` expression.
///
/// Inputs:
/// - `value`: CoreIR binary/atom payload, often already carrying source quotes.
///
/// Output:
/// - Rust expression that constructs an owned `String`.
///
/// Transformation:
/// - Reuses quoted source literals when present and otherwise escapes the raw
///   payload into a Rust string literal.
fn rust_string_expr(value: &str) -> String {
    if value.starts_with('"') && value.ends_with('"') {
        format!("String::from({value})")
    } else {
        format!("String::from({})", rust_string_literal(value))
    }
}

/// Escapes text as a Rust string literal.
///
/// Inputs:
/// - `value`: unescaped source text.
///
/// Output:
/// - Double-quoted Rust string literal.
///
/// Transformation:
/// - Escapes backslash, quote, newline, carriage return, and tab characters.
fn rust_string_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// Returns a Rust-safe identifier for known-safe Terlan names.
///
/// Inputs:
/// - `name`: Terlan/CoreIR identifier.
///
/// Output:
/// - Rust identifier text, with raw-identifier escaping for reserved words.
///
/// Transformation:
/// - Preserves normal identifiers and prefixes Rust keywords with `r#`.
fn rust_identifier(name: &str) -> String {
    if is_rust_keyword(name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Checks whether text is representable as a Rust identifier.
///
/// Inputs:
/// - `name`: candidate identifier text.
///
/// Output:
/// - `true` for ASCII Rust identifiers accepted by the native probe.
///
/// Transformation:
/// - Applies the conservative identifier subset used by current CoreIR tests:
///   ASCII alphabetic or underscore start, followed by ASCII alphanumeric or
///   underscores.
fn is_rust_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(first) if first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

/// Checks whether an identifier is a Rust keyword requiring raw escaping.
///
/// Inputs:
/// - `name`: identifier candidate.
///
/// Output:
/// - `true` when Rust requires raw-identifier syntax for the name.
///
/// Transformation:
/// - Encodes the small keyword set that may plausibly occur in Terlan source
///   fixtures without importing parser internals.
fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;
    use crate::formal_pipeline::compile_syntax_module_through_phases_with_profile;
    use crate::validation::native_policy::NativePolicy;
    use crate::validation::target_profile::TargetProfile;
    use crate::DiagnosticFormat;
    use terlan_hir::ModuleInterface;
    use terlan_typeck::{
        CoreExport, CoreExportKind, CoreExprSummary, CoreFunctionClause, CoreModuleMetadata,
        CoreParam, CoreProofCoverage, CoreProofReadiness, CoreSourceIdentity, CORE_IR_SCHEMA,
    };

    /// Verifies Rust probe emission preserves CoreIR function visibility.
    ///
    /// Inputs:
    /// - A Terlan module with one public function and one private helper.
    ///
    /// Output:
    /// - Test passes when emitted Rust contains `pub fn` for the public
    ///   function and plain `fn` for the private helper.
    ///
    /// Transformation:
    /// - Compiles Terlan source through the formal pipeline, emits Rust from
    ///   CoreIR, and inspects the generated source surface.
    #[test]
    fn emit_core_module_to_rust_uses_core_function_visibility() {
        let source = "\
module rust_core_surface.

pub add(x: Int, y: Int): Int ->
    x + y.

hidden(x: Int): Int ->
    x.
";
        let rust = compile_source_to_rust_probe("rust_core_surface.tl", source);

        assert!(rust.contains("pub fn add(x: i64, y: i64) -> i64"), "{rust}");
        assert!(rust.contains("fn hidden(x: i64) -> i64"), "{rust}");
    }

    /// Verifies Rust probe emission handles local calls and pipe-forward CoreIR.
    ///
    /// Inputs:
    /// - A Terlan module with a public helper call and `|>` expression.
    ///
    /// Output:
    /// - Test passes when emitted Rust contains the expected local-call shape
    ///   and compiles as a Rust library.
    ///
    /// Transformation:
    /// - Exercises the formal Terlan-to-CoreIR pipeline, emits Rust from CoreIR,
    ///   and invokes `rustc --crate-type lib` as a native neutrality check.
    #[test]
    fn emit_core_module_to_rust_compiles_pipe_forward_probe() {
        let source = "\
module rust_core_surface_pipe.

pub add(x: Int, y: Int): Int ->
    x + y.

pub piped(): Int ->
    1 |> add(2).
";
        let rust = compile_source_to_rust_probe("rust_core_surface_pipe.tl", source);

        assert!(rust.contains("pub fn piped() -> i64"), "{rust}");
        assert!(rust.contains("add(1, 2)"), "{rust}");
        assert_rust_probe_compiles(&rust);
    }

    /// Verifies Rust probe emission handles function-value invocation CoreIR.
    ///
    /// Inputs:
    /// - None; constructs a focused CoreIR module with a callable parameter.
    ///
    /// Output:
    /// - Test passes when emitted Rust contains `(f)(10)` and compiles.
    ///
    /// Transformation:
    /// - Bypasses parser syntax so the native probe directly exercises the
    ///   backend-neutral `CoreExpr::FunctionCall` payload.
    #[test]
    fn emit_core_module_to_rust_handles_function_value_call() {
        let module = core_module_with_functions(
            "rust_callable_probe",
            vec![CoreFunction {
                name: "apply".to_string(),
                arity: 1,
                public: true,
                params: vec![CoreParam {
                    name: "f".to_string(),
                    ty: "Term".to_string(),
                    core_ty: Some(CoreType::Arrow {
                        params: vec![CoreType::Int],
                        return_type: Box::new(CoreType::Int),
                    }),
                }],
                return_type: "Int".to_string(),
                core_return_type: Some(CoreType::Int),
                clauses: vec![CoreFunctionClause {
                    patterns: vec!["f".to_string()],
                    core_patterns: vec![Some(CorePattern::Var("f".to_string()))],
                    pattern_proof_coverage: Vec::new(),
                    pattern_checked_preservation_evidence: Vec::new(),
                    guard: None,
                    body: direct_expr_summary(CoreExpr::FunctionCall {
                        callee: Box::new(CoreExpr::Var("f".to_string())),
                        args: vec![CoreExpr::Int(10)],
                    }),
                }],
            }],
        );

        let rust = emit_core_module_to_rust(&module);

        assert!(rust.contains("(f)(10)"), "{rust}");
        assert_rust_probe_compiles(&rust);
    }

    /// Verifies Rust probe emission handles selected primitive CoreIR intrinsics.
    ///
    /// Inputs:
    /// - A Terlan module that calls the receiver-style string method
    ///   `"hello".contains("ell")`.
    ///
    /// Output:
    /// - Test passes when emitted Rust contains the Rust string containment
    ///   operation and compiles as a library.
    ///
    /// Transformation:
    /// - Compiles source through parser, typechecking, and CoreIR lowering so
    ///   the receiver method becomes `core.string.contains`, then verifies the
    ///   Rust/native probe lowers that backend-neutral intrinsic.
    #[test]
    fn emit_core_module_to_rust_compiles_string_contains_intrinsic_probe() {
        let source = "\
module rust_core_surface_string_intrinsic.

pub has_needle(): Bool ->
    \"hello\".contains(\"ell\").
";
        let rust = compile_source_to_rust_probe("rust_core_surface_string_intrinsic.tl", source);

        assert!(rust.contains(".contains("), "{rust}");
        assert!(rust.contains(".as_str()"), "{rust}");
        assert_rust_probe_compiles(&rust);
    }

    /// Verifies Rust probe emission handles string-prefix primitive intrinsics.
    ///
    /// Inputs:
    /// - A Terlan module that calls the receiver-style string method
    ///   `"hello".starts_with("he")`.
    ///
    /// Output:
    /// - Test passes when emitted Rust uses the Rust string-prefix operation
    ///   and compiles as a library.
    ///
    /// Transformation:
    /// - Compiles source through parser, typechecking, and CoreIR lowering so
    ///   the receiver method becomes `core.string.starts_with`, then verifies
    ///   the Rust/native probe lowers that backend-neutral intrinsic.
    #[test]
    fn emit_core_module_to_rust_compiles_string_starts_with_intrinsic_probe() {
        let source = "\
module rust_core_surface_string_starts_with_intrinsic.

pub has_prefix(): Bool ->
    \"hello\".starts_with(\"he\").
";
        let rust = compile_source_to_rust_probe(
            "rust_core_surface_string_starts_with_intrinsic.tl",
            source,
        );

        assert!(rust.contains(".starts_with("), "{rust}");
        assert!(rust.contains(".as_str()"), "{rust}");
        assert_rust_probe_compiles(&rust);
    }

    /// Verifies Rust probe emission handles text-length primitive intrinsics.
    ///
    /// Inputs:
    /// - A Terlan module that calls the receiver-style string method
    ///   `"hello".length()`.
    ///
    /// Output:
    /// - Test passes when emitted Rust counts Unicode scalar values and
    ///   compiles as a library.
    ///
    /// Transformation:
    /// - Compiles source through parser, typechecking, and CoreIR lowering so
    ///   the receiver method becomes `core.string.length`, then verifies the
    ///   Rust/native probe lowers that backend-neutral intrinsic to a text
    ///   length expression rather than a byte-size expression.
    #[test]
    fn emit_core_module_to_rust_compiles_string_length_intrinsic_probe() {
        let source = "\
module rust_core_surface_string_length_intrinsic.

pub len(): Int ->
    \"hello\".length().
";
        let rust =
            compile_source_to_rust_probe("rust_core_surface_string_length_intrinsic.tl", source);

        assert!(rust.contains(".chars().count() as i64"), "{rust}");
        assert_rust_probe_compiles(&rust);
    }

    /// Compiles Terlan source into Rust probe source.
    ///
    /// Inputs:
    /// - `path`: diagnostic source path.
    /// - `source`: Terlan module text.
    ///
    /// Output:
    /// - Rust source emitted from the checked CoreIR module.
    ///
    /// Transformation:
    /// - Runs the formal compiler pipeline with default profile settings and
    ///   passes the resulting CoreIR to the Rust/native probe emitter.
    fn compile_source_to_rust_probe(path: &str, source: &str) -> String {
        let artifacts = compile_syntax_module_through_phases_with_profile(
            path,
            source,
            DiagnosticFormat::default(),
            None,
            NativePolicy::default(),
            TargetProfile::default(),
        )
        .expect("compile source to CoreIR");

        emit_core_module_to_rust(&artifacts.core)
    }

    /// Builds a focused CoreModule for direct Rust probe tests.
    ///
    /// Inputs:
    /// - `module`: module identity to place in CoreIR metadata and interface.
    /// - `functions`: already-constructed CoreIR function declarations.
    ///
    /// Output:
    /// - `CoreModule` with empty imports/types/constructors and zeroed metadata.
    ///
    /// Transformation:
    /// - Wraps direct test functions in the current CoreIR module shape without
    ///   depending on parser fixtures or backend-specific resolver data.
    fn core_module_with_functions(module: &str, functions: Vec<CoreFunction>) -> CoreModule {
        CoreModule {
            schema: CORE_IR_SCHEMA.to_string(),
            module: module.to_string(),
            source: CoreSourceIdentity {
                source_kind: "direct-test".to_string(),
                syntax_contract_fingerprint: None,
            },
            imports: Vec::new(),
            exports: functions
                .iter()
                .filter(|function| function.public)
                .map(|function| CoreExport {
                    name: function.name.clone(),
                    kind: CoreExportKind::Function {
                        arity: function.arity,
                    },
                })
                .collect(),
            types: Vec::new(),
            functions,
            constructors: Vec::new(),
            trait_conformances: Vec::new(),
            metadata: empty_core_metadata(),
            interface: empty_interface(module),
        }
    }

    /// Builds a minimal Core expression summary around a direct test expression.
    ///
    /// Inputs:
    /// - `expr`: typed CoreIR expression to attach to the summary.
    ///
    /// Output:
    /// - `CoreExprSummary` using Lean-covered test metadata.
    ///
    /// Transformation:
    /// - Packages a typed Core expression into the summary shape expected by
    ///   Core function clauses while leaving source-only metadata empty.
    fn direct_expr_summary(expr: CoreExpr) -> CoreExprSummary {
        CoreExprSummary {
            kind: "direct-test".to_string(),
            core_expr: Some(expr),
            checked_preservation_evidence: None,
            proof_coverage: CoreProofCoverage::LeanCovered,
            text: None,
            remote: None,
            operator: None,
            arity: 0,
            children: Vec::new(),
        }
    }

    /// Builds zeroed Core module metadata for direct probe fixtures.
    ///
    /// Inputs:
    /// - None.
    ///
    /// Output:
    /// - `CoreModuleMetadata` with no counts and `LeanCovered` readiness.
    ///
    /// Transformation:
    /// - Provides deterministic metadata for tests that inspect emission rather
    ///   than proof accounting.
    fn empty_core_metadata() -> CoreModuleMetadata {
        CoreModuleMetadata {
            interface_function_count: 0,
            interface_type_count: 0,
            constructor_count: 0,
            proof_readiness: CoreProofReadiness::LeanCovered,
            lean_covered_expr_count: 0,
            partial_expr_count: 0,
            proof_model_required_expr_count: 0,
            runtime_boundary_expr_count: 0,
            artifact_only_expr_count: 0,
            lean_covered_pattern_count: 0,
            partial_pattern_count: 0,
            proof_model_required_pattern_count: 0,
            runtime_boundary_pattern_count: 0,
            artifact_only_pattern_count: 0,
            typed_core_expr_count: 0,
            summary_only_expr_count: 0,
            typed_core_pattern_count: 0,
            summary_only_pattern_count: 0,
            typed_core_type_count: 0,
            summary_only_type_count: 0,
            checked_preservation_expr_count: 0,
            checked_preservation_pattern_count: 0,
            checked_preservation_expr_structural_count: 0,
            checked_preservation_pattern_structural_count: 0,
            checked_preservation_expr_no_runtime_bindings_count: 0,
            checked_preservation_pattern_no_runtime_bindings_count: 0,
            checked_preservation_expr_runtime_bindings_required_count: 0,
            checked_preservation_pattern_runtime_bindings_required_count: 0,
            resolved_constructor_call_identity_count: 0,
            resolved_constructor_chain_identity_count: 0,
            resolved_constructor_pattern_identity_count: 0,
            unresolved_constructor_call_candidate_count: 0,
            unresolved_constructor_chain_candidate_count: 0,
            unresolved_constructor_pattern_candidate_count: 0,
        }
    }

    /// Builds an empty module interface for direct probe fixtures.
    ///
    /// Inputs:
    /// - `module`: module identity for the interface.
    ///
    /// Output:
    /// - `ModuleInterface` with no public declarations.
    ///
    /// Transformation:
    /// - Uses empty maps and sets because Rust probe tests read CoreIR
    ///   functions directly and do not inspect interface rendering.
    fn empty_interface(module: &str) -> ModuleInterface {
        ModuleInterface {
            module: module.to_string(),
            docs: Vec::new(),
            public_types: HashSet::new(),
            private_types: HashSet::new(),
            opaque_types: HashSet::new(),
            type_params: HashMap::new(),
            type_bodies: HashMap::new(),
            type_docs: HashMap::new(),
            traits: HashMap::new(),
            trait_conformances: Vec::new(),
            constructors: HashMap::new(),
            functions: HashMap::new(),
        }
    }

    /// Asserts that generated Rust probe source compiles as a library.
    ///
    /// Inputs:
    /// - `source`: generated Rust source text.
    ///
    /// Output:
    /// - Test assertion success when `rustc` exits successfully.
    ///
    /// Transformation:
    /// - Writes the source to a temporary file, invokes `rustc --crate-type lib`,
    ///   and removes the temporary directory after the check.
    fn assert_rust_probe_compiles(source: &str) {
        let dir = unique_temp_dir("terlan_rust_probe");
        fs::create_dir_all(&dir).expect("create rust probe temp dir");
        let source_path = dir.join("probe.rs");
        let output_path = dir.join("libprobe.rlib");
        fs::write(&source_path, source).expect("write rust probe source");

        let output = Command::new("rustc")
            .arg("--edition=2021")
            .arg("--crate-type")
            .arg("lib")
            .arg(&source_path)
            .arg("-o")
            .arg(&output_path)
            .output()
            .expect("run rustc");
        let _ = fs::remove_dir_all(&dir);

        assert!(
            output.status.success(),
            "rustc failed\nsource:\n{}\nstdout:\n{}\nstderr:\n{}",
            source,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    /// Builds a unique temporary directory path for test artifacts.
    ///
    /// Inputs:
    /// - `prefix`: human-readable temp directory prefix.
    ///
    /// Output:
    /// - Path in the process temp directory that is very unlikely to exist.
    ///
    /// Transformation:
    /// - Combines temp directory, process id, current nanosecond timestamp, and
    ///   caller prefix into a deterministic path string for this test run.
    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time after unix epoch")
            .as_nanos();
        Path::new(&std::env::temp_dir()).join(format!(
            "{}_{}_{}",
            prefix,
            std::process::id(),
            nanos
        ))
    }
}
