use terlan_typeck::{
    CoreExpr, CoreFunction, CoreIntrinsicCall, CoreIntrinsicId, CoreModule, CorePattern,
    CorePrimitiveIntrinsic, CoreType,
};

/// Emits a narrow Rust/native probe artifact from CoreIR.
///
/// Inputs:
/// - `module`: backend-independent CoreIR module produced by the formal
///   compiler pipeline.
///
/// Output:
/// - Rust source text for functions currently supported by the native
///   neutrality probe.
///
/// Transformation:
/// - Converts CoreIR function signatures and a selected expression subset into
///   plain Rust functions, preserving public/private visibility while rejecting
///   unsupported bodies into explicit `unimplemented!()` stubs.
pub(crate) fn emit_core_module_to_rust(module: &CoreModule) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Terlan Rust/native neutrality probe.\n");
    out.push_str("// This is not a release backend artifact.\n\n");

    for function in &module.functions {
        out.push_str(&emit_core_function_to_rust(function));
        out.push('\n');
    }

    out
}

/// Emits one CoreIR function as Rust source.
///
/// Inputs:
/// - `function`: CoreIR function signature and clause set.
///
/// Output:
/// - Rust function declaration text.
///
/// Transformation:
/// - Maps CoreIR visibility, parameter types, return type, and supported
///   single-clause bodies into Rust syntax; unsupported bodies stay explicit
///   stubs so the probe remains compilable without inventing semantics.
fn emit_core_function_to_rust(function: &CoreFunction) -> String {
    let visibility = if function.public { "pub " } else { "" };
    let params = function
        .params
        .iter()
        .map(|param| {
            format!(
                "{}: {}",
                rust_identifier(&param.name),
                core_type_to_rust(param.core_ty.as_ref(), &param.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let return_type = core_type_to_rust(function.core_return_type.as_ref(), &function.return_type);
    let body = emit_core_function_body_to_rust(function).unwrap_or_else(|| {
        "    unimplemented!(\"unsupported Terlan Rust probe body\")\n".to_string()
    });

    format!(
        "{visibility}fn {}({params}) -> {return_type} {{\n{body}}}\n",
        rust_identifier(&function.name)
    )
}

/// Lowers one CoreIR function body into Rust when it is in the supported subset.
///
/// Inputs:
/// - `function`: CoreIR function whose clause body may be emitted.
///
/// Output:
/// - Rust function body text for supported single-clause functions.
/// - `None` for unsupported clauses, guards, patterns, or expressions.
///
/// Transformation:
/// - Accepts one unguarded clause with direct variable patterns matching the
///   declared parameters, then emits the CoreIR expression as the function's
///   final Rust expression.
fn emit_core_function_body_to_rust(function: &CoreFunction) -> Option<String> {
    let [clause] = function.clauses.as_slice() else {
        return None;
    };
    if clause.guard.is_some() {
        return None;
    }
    if !core_clause_patterns_match_function_params(function, &clause.core_patterns) {
        return None;
    }
    Some(format!(
        "    {}\n",
        core_expr_to_rust(clause.body.core_expr.as_ref()?)?
    ))
}

/// Checks whether CoreIR clause patterns are direct parameter bindings.
///
/// Inputs:
/// - `function`: function whose parameter list defines the Rust callable
///   surface.
/// - `patterns`: CoreIR clause parameter patterns.
///
/// Output:
/// - `true` when every pattern is the same variable as its corresponding
///   parameter.
///
/// Transformation:
/// - Rejects destructuring and literal-pattern dispatch so the first native
///   probe slice does not choose Rust pattern lowering semantics prematurely.
fn core_clause_patterns_match_function_params(
    function: &CoreFunction,
    patterns: &[Option<CorePattern>],
) -> bool {
    function.params.len() == patterns.len()
        && function
            .params
            .iter()
            .zip(patterns.iter())
            .all(|(param, pattern)| {
                matches!(pattern, Some(CorePattern::Var(name)) if name == &param.name)
                    && is_rust_identifier(&param.name)
            })
}

/// Lowers a supported CoreIR expression into Rust expression text.
///
/// Inputs:
/// - `expr`: typed CoreIR expression.
///
/// Output:
/// - Rust expression text for the current native probe subset.
/// - `None` for CoreIR forms that still need target semantics.
///
/// Transformation:
/// - Recursively emits portable scalar values, local calls, callable-value
///   calls, pipe-forward calls, unary negation, and selected binary operators
///   without reading source syntax or backend-specific metadata.
fn core_expr_to_rust(expr: &CoreExpr) -> Option<String> {
    match expr {
        CoreExpr::Int(value) => Some(value.to_string()),
        CoreExpr::Float(value) => rust_float_literal(value),
        CoreExpr::Atom(value) | CoreExpr::Var(value) if value == "true" || value == "false" => {
            Some(value.clone())
        }
        CoreExpr::Binary(value) | CoreExpr::Atom(value) => Some(rust_string_expr(value)),
        CoreExpr::Var(name) if is_rust_identifier(name) => Some(rust_identifier(name)),
        CoreExpr::Call { function, args } => core_call_expr_to_rust(function, args),
        CoreExpr::FunctionCall { callee, args } => core_function_call_expr_to_rust(callee, args),
        CoreExpr::Intrinsic(call) => core_intrinsic_call_expr_to_rust(call),
        CoreExpr::UnaryOp { operator, operand } if operator == "-" => {
            Some(format!("(-{})", core_expr_to_rust(operand)?))
        }
        CoreExpr::BinaryOp {
            operator,
            left,
            right,
        } => {
            if operator == "|>" {
                return core_pipe_forward_expr_to_rust(left, right);
            }
            if operator == "div" {
                return Some(format!(
                    "({} / {})",
                    core_expr_to_rust(left)?,
                    core_expr_to_rust(right)?
                ));
            }
            let operator = rust_binary_operator(operator)?;
            Some(format!(
                "({} {} {})",
                core_expr_to_rust(left)?,
                operator,
                core_expr_to_rust(right)?
            ))
        }
        _ => None,
    }
}

/// Lowers a supported CoreIR intrinsic call into Rust expression text.
///
/// Inputs:
/// - `call`: CoreIR intrinsic call with a closed backend-neutral intrinsic id.
///
/// Output:
/// - Rust expression text for the supported intrinsic subset.
/// - `None` when the intrinsic has no selected Rust/native probe lowering yet.
///
/// Transformation:
/// - Maps compiler-owned primitive intrinsic ids to Rust standard-library
///   operations without exposing Rust names back into CoreIR or source syntax.
fn core_intrinsic_call_expr_to_rust(call: &CoreIntrinsicCall) -> Option<String> {
    match &call.id {
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringContains) => {
            let [value, pattern] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "{}.contains({}.as_str())",
                core_expr_to_rust(value)?,
                core_expr_to_rust(pattern)?
            ))
        }
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringStartsWith) => {
            let [value, prefix] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "{}.starts_with({}.as_str())",
                core_expr_to_rust(value)?,
                core_expr_to_rust(prefix)?
            ))
        }
        CoreIntrinsicId::Primitive(CorePrimitiveIntrinsic::StringLength) => {
            let [value] = call.args.as_slice() else {
                return None;
            };
            Some(format!(
                "({}.chars().count() as i64)",
                core_expr_to_rust(value)?
            ))
        }
        _ => None,
    }
}

/// Lowers a local named CoreIR call into Rust expression text.
///
/// Inputs:
/// - `function`: local CoreIR function name.
/// - `args`: CoreIR argument expressions.
///
/// Output:
/// - Rust call expression text, or `None` for unsupported names/arguments.
///
/// Transformation:
/// - Emits `function(arg1, arg2, ...)` with sanitized Rust identifiers.
fn core_call_expr_to_rust(function: &str, args: &[CoreExpr]) -> Option<String> {
    if !is_rust_identifier(function) {
        return None;
    }
    let args = args
        .iter()
        .map(core_expr_to_rust)
        .collect::<Option<Vec<_>>>()?
        .join(", ");
    Some(format!("{}({args})", rust_identifier(function)))
}

/// Lowers a CoreIR function-value invocation into Rust expression text.
///
/// Inputs:
/// - `callee`: CoreIR expression that should evaluate to a callable value.
/// - `args`: CoreIR argument expressions.
///
/// Output:
/// - Rust call expression text, or `None` for unsupported callees/arguments.
///
/// Transformation:
/// - Emits `(callee)(args...)`, preserving Terlan's `f.(args)` distinction from
///   named calls without selecting a closure runtime beyond Rust's callable
///   expression syntax.
fn core_function_call_expr_to_rust(callee: &CoreExpr, args: &[CoreExpr]) -> Option<String> {
    let callee = core_expr_to_rust(callee)?;
    let args = args
        .iter()
        .map(core_expr_to_rust)
        .collect::<Option<Vec<_>>>()?
        .join(", ");
    Some(format!("({callee})({args})"))
}

/// Lowers a focused CoreIR pipe-forward expression into Rust call syntax.
///
/// Inputs:
/// - `left`: piped CoreIR value.
/// - `right`: CoreIR call expression receiving the piped value.
///
/// Output:
/// - Rust call expression text for supported pipe targets.
/// - `None` when the right side is not a named or function-value call.
///
/// Transformation:
/// - Converts `value |> f(extra)` into `f(value, extra)` and `value |> f.(extra)`
///   into `(f)(value, extra)`.
fn core_pipe_forward_expr_to_rust(left: &CoreExpr, right: &CoreExpr) -> Option<String> {
    match right {
        CoreExpr::Call { function, args } => {
            if !is_rust_identifier(function) {
                return None;
            }
            let mut emitted_args = vec![core_expr_to_rust(left)?];
            emitted_args.extend(
                args.iter()
                    .map(core_expr_to_rust)
                    .collect::<Option<Vec<_>>>()?,
            );
            Some(format!(
                "{}({})",
                rust_identifier(function),
                emitted_args.join(", ")
            ))
        }
        CoreExpr::FunctionCall { callee, args } => {
            let callee = core_expr_to_rust(callee)?;
            let mut emitted_args = vec![core_expr_to_rust(left)?];
            emitted_args.extend(
                args.iter()
                    .map(core_expr_to_rust)
                    .collect::<Option<Vec<_>>>()?,
            );
            Some(format!("({callee})({})", emitted_args.join(", ")))
        }
        _ => None,
    }
}

/// Maps a CoreIR type into the Rust probe type surface.
///
/// Inputs:
/// - `core_type`: structured CoreIR type, when available.
/// - `fallback`: source-level type text for functions that do not yet carry a
///   structured type payload.
///
/// Output:
/// - Rust type text accepted by the native probe.
///
/// Transformation:
/// - Prefers structured CoreIR types and falls back to source type names,
///   mapping unknown terms to `()` so unsupported shapes remain explicit
///   compile-time placeholders rather than backend-specific runtime values.
fn core_type_to_rust(core_type: Option<&CoreType>, fallback: &str) -> String {
    match core_type {
        Some(CoreType::Int) => "i64".to_string(),
        Some(CoreType::Float) | Some(CoreType::Number) => "f64".to_string(),
        Some(CoreType::Bool) => "bool".to_string(),
        Some(CoreType::String) | Some(CoreType::Binary) => "String".to_string(),
        Some(CoreType::Never) => "!".to_string(),
        Some(CoreType::Arrow {
            params,
            return_type,
        }) => format!(
            "fn({}) -> {}",
            params
                .iter()
                .map(|param| core_type_to_rust(Some(param), "Term"))
                .collect::<Vec<_>>()
                .join(", "),
            core_type_to_rust(Some(return_type), "Term")
        ),
        Some(CoreType::Term) | Some(CoreType::Dynamic) | None => match fallback {
            "Int" => "i64".to_string(),
            "Float" | "Number" => "f64".to_string(),
            "Bool" => "bool".to_string(),
            "String" | "Binary" | "Text" => "String".to_string(),
            "Never" => "!".to_string(),
            _ => "()".to_string(),
        },
        _ => "()".to_string(),
    }
}

/// Maps a CoreIR binary operator into Rust.
///
/// Inputs:
/// - `operator`: normalized CoreIR binary operator token.
///
/// Output:
/// - Rust operator token for the supported subset.
/// - `None` for operators requiring target-specific semantics.
///
/// Transformation:
/// - Keeps arithmetic and comparison operators textual while preserving the
///   Terlan `==` / `!=` equality surface.
fn rust_binary_operator(operator: &str) -> Option<&'static str> {
    match operator {
        "+" => Some("+"),
        "-" => Some("-"),
        "*" => Some("*"),
        "/" => Some("/"),
        "==" => Some("=="),
        "!=" => Some("!="),
        ">" => Some(">"),
        ">=" => Some(">="),
        "<" => Some("<"),
        "<=" => Some("<="),
        "and" | "&&" => Some("&&"),
        "or" | "||" => Some("||"),
        _ => None,
    }
}

/// Converts a CoreIR float payload into a Rust float literal.
///
/// Inputs:
/// - `value`: CoreIR float payload text.
///
/// Output:
/// - Rust finite float literal text.
/// - `None` for non-finite or unparsable payloads.
///
/// Transformation:
/// - Parses through `f64` to reject non-portable float payloads before native
///   probe emission.
fn rust_float_literal(value: &str) -> Option<String> {
    let parsed = value.parse::<f64>().ok()?;
    parsed.is_finite().then(|| value.to_string())
}

/// Converts a CoreIR string-like payload into a Rust `String` expression.
///
/// Inputs:
/// - `value`: CoreIR binary/atom payload, often already carrying source quotes.
///
/// Output:
/// - Rust expression that constructs an owned `String`.
///
/// Transformation:
/// - Reuses quoted source literals when present and otherwise escapes the raw
///   payload into a Rust string literal.
fn rust_string_expr(value: &str) -> String {
    if value.starts_with('"') && value.ends_with('"') {
        format!("String::from({value})")
    } else {
        format!("String::from({})", rust_string_literal(value))
    }
}

/// Escapes text as a Rust string literal.
///
/// Inputs:
/// - `value`: unescaped source text.
///
/// Output:
/// - Double-quoted Rust string literal.
///
/// Transformation:
/// - Escapes backslash, quote, newline, carriage return, and tab characters.
fn rust_string_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// Returns a Rust-safe identifier for known-safe Terlan names.
///
/// Inputs:
/// - `name`: Terlan/CoreIR identifier.
///
/// Output:
/// - Rust identifier text, with raw-identifier escaping for reserved words.
///
/// Transformation:
/// - Preserves normal identifiers and prefixes Rust keywords with `r#`.
fn rust_identifier(name: &str) -> String {
    if is_rust_keyword(name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Checks whether text is representable as a Rust identifier.
///
/// Inputs:
/// - `name`: candidate identifier text.
///
/// Output:
/// - `true` for ASCII Rust identifiers accepted by the native probe.
///
/// Transformation:
/// - Applies the conservative identifier subset used by current CoreIR tests:
///   ASCII alphabetic or underscore start, followed by ASCII alphanumeric or
///   underscores.
fn is_rust_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(first) if first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

/// Checks whether an identifier is a Rust keyword requiring raw escaping.
///
/// Inputs:
/// - `name`: identifier candidate.
///
/// Output:
/// - `true` when Rust requires raw-identifier syntax for the name.
///
/// Transformation:
/// - Encodes the small keyword set that may plausibly occur in Terlan source
///   fixtures without importing parser internals.
fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

#[cfg(test)]
#[path = "emit_rust_test.rs"]
mod emit_rust_test;
