[package]
name = "terlan-archive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
flate2 = "1.1.9"
tar.workspace = true
zip = { version = "6.0.0", default-features = false, features = ["deflate-flate2"] }
zstd.workspace = true
