use std::env;
use std::process::ExitCode;

use crate::runtime::vm::{
    postgres::{VmPostgresDecodedValue, VmPostgresRow},
    postgres_command::VmPostgresCommandClient,
};
use crate::terlan_native::json;
use crate::terlan_native::postgres;
use base64::engine::general_purpose::STANDARD;
use base64::Engine;

/// Executes the private compiler SQL runtime helper.
///
/// Inputs:
/// - `args`: `operation transaction_requirement sql_base64 params_json_base64
///   projection_base64`.
///
/// Output:
/// - Exit success with a line-oriented response consumed by VM/native-boundary
///   SQL callers.
/// - Exit failure only for malformed helper invocation; database/query errors
///   are encoded as runtime `err` responses so generated VM callers receive a
///   normal `Result`.
///
/// Transformation:
/// - Decodes the private protocol, resolves the process database environment,
///   delegates execution to the maintained NativeBoundary Postgres adapter, and
///   serializes typed projected row values without exposing this protocol as a
///   public Terlan API.
pub(crate) fn run(args: &[String]) -> ExitCode {
    match run_inner(args) {
        Ok(output) => {
            print!("{output}");
            ExitCode::SUCCESS
        }
        Err(error) => {
            println!("err");
            println!("{}", encode_text(&error));
            ExitCode::SUCCESS
        }
    }
}

/// Runs the decoded SQL helper request.
///
/// Inputs:
/// - `args`: encoded helper arguments after the private subcommand name.
///
/// Output:
/// - Encoded success payload for VM or a runtime error message.
///
/// Transformation:
/// - Decodes helper arguments, opens the configured Postgres pool, dispatches
///   the requested operation, and serializes the projected result.
fn run_inner(args: &[String]) -> Result<String, String> {
    let [operation, transaction_requirement, sql, params, projection] = args else {
        return Err(
            "terlc __sql-runtime expects operation, transaction requirement, SQL, params, and projection arguments".to_string(),
        );
    };
    let operation = SqlRuntimeOperation::parse(operation)?;
    SqlRuntimeTransactionRequirement::parse(transaction_requirement)?.require_autocommit()?;
    let sql = decode_text(sql)?;
    let params = decode_params(params)?;
    let projection = decode_projection(projection)?;
    let config = database_config()?;
    let mut client = VmPostgresCommandClient::connect(&config)?;
    match operation {
        SqlRuntimeOperation::QueryOne => {
            let row = client.query_one(&sql, params)?;
            match row {
                Some(row) => Ok(format!(
                    "ok_one\n{}\n",
                    encode_row(&mut client, row, &projection)?
                )),
                None => Ok("ok_none\n".to_string()),
            }
        }
        SqlRuntimeOperation::Query => {
            let rows = client.query(&sql, params)?;
            let mut output = String::from("ok_rows\n");
            for row in rows {
                output.push_str(&encode_row(&mut client, row, &projection)?);
                output.push('\n');
            }
            Ok(output)
        }
        SqlRuntimeOperation::Execute => {
            let affected = client.execute(&sql, params)?;
            Ok(format!("ok_int\n{affected}\n"))
        }
    }
}

/// Transaction contract carried from CoreIR SQL metadata into runtime dispatch.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SqlRuntimeTransactionRequirement {
    AutocommitAllowed,
    ActiveTransactionRequired,
    VmManagedControl,
}

impl SqlRuntimeTransactionRequirement {
    fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "autocommit_allowed" => Ok(Self::AutocommitAllowed),
            "active_transaction_required" => Ok(Self::ActiveTransactionRequired),
            "vm_managed_control" => Ok(Self::VmManagedControl),
            other => Err(format!(
                "unsupported SQL runtime transaction requirement `{other}`"
            )),
        }
    }

    fn require_autocommit(self) -> Result<(), String> {
        match self {
            Self::AutocommitAllowed => Ok(()),
            Self::ActiveTransactionRequired => Err(
                "SQL operation requires an active typed VM transaction; autocommit dispatch is forbidden"
                    .to_string(),
            ),
            Self::VmManagedControl => Err(
                "SQL transaction control is VM-owned and cannot execute through the SQL runtime helper"
                    .to_string(),
            ),
        }
    }
}

/// SQL helper operations generated by compiler-owned SQL lowering.
///
/// Inputs:
/// - Source-level SQL wrapper cardinality lowered by the compiler.
///
/// Output:
/// - Closed operation enum for dispatch.
///
/// Transformation:
/// - Keeps private helper dispatch finite and validates operation names before
///   opening a database connection.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SqlRuntimeOperation {
    /// Query returning many rows.
    Query,
    /// Query returning at most one row.
    QueryOne,
    /// Command returning affected row count.
    Execute,
}

impl SqlRuntimeOperation {
    /// Parses a private SQL helper operation name.
    ///
    /// Inputs:
    /// - `raw`: operation text from generated VM helper arguments.
    ///
    /// Output:
    /// - Closed SQL operation enum.
    /// - Stable error for unsupported operation names.
    ///
    /// Transformation:
    /// - Rejects malformed helper invocations before runtime config lookup,
    ///   connection setup, or SQL execution.
    fn parse(raw: &str) -> Result<Self, String> {
        match raw {
            "query" => Ok(Self::Query),
            "query_one" => Ok(Self::QueryOne),
            "execute" => Ok(Self::Execute),
            other => Err(format!("unsupported SQL runtime operation `{other}`")),
        }
    }
}

/// Builds the Postgres configuration from process environment.
///
/// Inputs:
/// - `TERLAN_DATABASE_URL`, or the `POSTGRES_*` environment variable set.
///
/// Output:
/// - Validated NativeBoundary Postgres config.
///
/// Transformation:
/// - Prefers a single URL and otherwise assembles a URL from conventional
///   Docker/Postgres environment variables.
fn database_config() -> Result<postgres::Config, String> {
    if let Ok(url) = env::var("TERLAN_DATABASE_URL") {
        return validated_database_config(url);
    }
    let host = env::var("POSTGRES_HOST")
        .map_err(|_| "TERLAN_DATABASE_URL or POSTGRES_HOST must be set".to_string())?;
    let user = env::var("POSTGRES_USER")
        .map_err(|_| "TERLAN_DATABASE_URL or POSTGRES_USER must be set".to_string())?;
    let password = env::var("POSTGRES_PASSWORD")
        .map_err(|_| "TERLAN_DATABASE_URL or POSTGRES_PASSWORD must be set".to_string())?;
    let database = env::var("POSTGRES_DB")
        .map_err(|_| "TERLAN_DATABASE_URL or POSTGRES_DB must be set".to_string())?;
    let port = env::var("POSTGRES_PORT").unwrap_or_else(|_| "5432".to_string());
    validated_database_config(format!(
        "postgres://{user}:{password}@{host}:{port}/{database}"
    ))
}

/// Validates a database URL and applies runtime pool bounds.
///
/// Inputs:
/// - `url`: Postgres connection URL.
///
/// Output:
/// - NativeBoundary Postgres config accepted by the adapter.
///
/// Transformation:
/// - Adds conservative pool limits and delegates URL validation to the
///   maintained Postgres adapter.
fn validated_database_config(url: String) -> Result<postgres::Config, String> {
    let config = postgres::Config::new(url).with_pool_limits(1, 4);
    postgres::validate_config(&config)
        .map_err(|error| format!("{}: {}", error.code(), error.message()))?;
    Ok(config)
}

/// Decodes a base64 UTF-8 helper argument.
///
/// Inputs:
/// - `encoded`: base64-encoded text argument.
///
/// Output:
/// - Decoded UTF-8 string or a stable protocol error.
///
/// Transformation:
/// - Converts the private shell-safe transport encoding back to text.
fn decode_text(encoded: &str) -> Result<String, String> {
    let bytes = STANDARD
        .decode(encoded)
        .map_err(|error| format!("invalid base64 SQL runtime argument: {error}"))?;
    String::from_utf8(bytes).map_err(|error| format!("SQL runtime argument is not UTF-8: {error}"))
}

/// Decodes query parameters from a base64 JSON array.
///
/// Inputs:
/// - `encoded`: base64-encoded JSON array.
///
/// Output:
/// - NativeBoundary JSON parameter list.
///
/// Transformation:
/// - Parses serde JSON and converts each value into the runtime JSON wrapper.
fn decode_params(encoded: &str) -> Result<Vec<json::Json>, String> {
    let text = decode_text(encoded)?;
    let value = serde_json::from_str::<serde_json::Value>(&text)
        .map_err(|error| format!("SQL runtime params are not valid JSON: {error}"))?;
    let serde_json::Value::Array(values) = value else {
        return Err("SQL runtime params must be a JSON array".to_string());
    };
    Ok(values.into_iter().map(json::Json::from_serde).collect())
}

/// Decodes the projected column list.
///
/// Inputs:
/// - `encoded`: base64-encoded newline-separated projection text.
///
/// Output:
/// - Ordered projected field names.
///
/// Transformation:
/// - Splits the private projection protocol into field identifiers.
fn decode_projection(encoded: &str) -> Result<Vec<String>, String> {
    let text = decode_text(encoded)?;
    if text.is_empty() {
        return Ok(Vec::new());
    }
    Ok(text.lines().map(str::to_string).collect())
}

/// Encodes one projected database row for the VM SQL runtime.
///
/// Inputs:
/// - `row`: NativeBoundary Postgres row.
/// - `projection`: ordered projected field names.
///
/// Output:
/// - Tab-separated field payloads in the private SQL runtime protocol.
///
/// Transformation:
/// - Encodes each requested field using typed prefixes.
fn encode_row(
    client: &mut VmPostgresCommandClient,
    row: VmPostgresRow,
    projection: &[String],
) -> Result<String, String> {
    projection
        .iter()
        .map(|field| encode_field(client, row, field))
        .collect::<Result<Vec<_>, _>>()
        .map(|fields| fields.join("\t"))
}

/// Encodes one typed database field.
///
/// Inputs:
/// - `row`: NativeBoundary Postgres row.
/// - `field`: projected column name.
///
/// Output:
/// - Private protocol field payload with a type prefix.
///
/// Transformation:
/// - Attempts supported scalar and JSON decoders in deterministic order.
fn encode_field(
    client: &mut VmPostgresCommandClient,
    row: VmPostgresRow,
    field: &str,
) -> Result<String, String> {
    client
        .decode_dynamic(row, field)
        .map(encode_decoded_value)
        .map_err(|error| {
            format!("SQL runtime could not decode projected column `{field}`: {error}")
        })
}

fn encode_decoded_value(value: VmPostgresDecodedValue) -> String {
    match value {
        #[cfg(any(
            test,
            all(feature = "postgres-libpq", not(feature = "serve-runtime-bin"))
        ))]
        VmPostgresDecodedValue::Null => "n:".to_string(),
        #[cfg(any(
            test,
            all(feature = "postgres-libpq", not(feature = "serve-runtime-bin"))
        ))]
        VmPostgresDecodedValue::Int(value) => format!("i:{value}"),
        #[cfg(any(
            test,
            all(feature = "postgres-libpq", not(feature = "serve-runtime-bin"))
        ))]
        VmPostgresDecodedValue::Bool(value) => format!("b:{value}"),
        #[cfg(any(
            test,
            all(feature = "postgres-libpq", not(feature = "serve-runtime-bin"))
        ))]
        VmPostgresDecodedValue::String(value) => format!("s:{}", encode_text(&value)),
        #[cfg(any(
            test,
            all(feature = "postgres-libpq", not(feature = "serve-runtime-bin"))
        ))]
        VmPostgresDecodedValue::Json(value) => format!("j:{}", encode_text(&value)),
    }
}

/// Encodes text for the shell-safe SQL helper protocol.
///
/// Inputs:
/// - `value`: text to encode.
///
/// Output:
/// - Base64 encoded string.
///
/// Transformation:
/// - Converts UTF-8 bytes to base64 without adding separators.
fn encode_text(value: &str) -> String {
    STANDARD.encode(value.as_bytes())
}

#[cfg(test)]
#[path = "sql_runtime_test.rs"]
#[cfg(test)]
mod sql_runtime_test;
