use std::path::Path;

use super::super::diagnostic::{LintDiagnostic, Severity};

const GENERATED_SOURCE_MANIFEST_RULE_ID: &str = "TL0804";
const GENERATED_SOURCE_MANIFEST_RULE_NAME: &str = "interop.generated-source-manifest";
const GENERATED_LINT_SUPPRESSION_RULE_ID: &str = "TL0805";
const GENERATED_LINT_SUPPRESSION_RULE_NAME: &str = "interop.generated-lint-suppression";
const GENERATED_SKIP_MANIFEST_RULE_ID: &str = "TL0806";
const GENERATED_SKIP_MANIFEST_RULE_NAME: &str = "interop.generated-skip-manifest";

/// Builds diagnostics for generated files missing source manifest metadata.
pub(super) fn generated_source_manifest_diagnostics(
    path: &Path,
    source: &str,
) -> Vec<LintDiagnostic> {
    let Some((line_index, column)) = first_generated_marker(source) else {
        return Vec::new();
    };
    if has_generated_source_manifest(source) {
        return Vec::new();
    }

    vec![LintDiagnostic {
        path: path.to_path_buf(),
        line: line_index + 1,
        column,
        rule_id: GENERATED_SOURCE_MANIFEST_RULE_ID,
        rule_name: GENERATED_SOURCE_MANIFEST_RULE_NAME,
        severity: Severity::Warning,
        message: "generated source must include source-manifest metadata",
        fix_available: false,
    }]
}

/// Builds diagnostics for generated files with unstructured lint suppressions.
pub(super) fn generated_lint_suppression_diagnostics(
    path: &Path,
    source: &str,
) -> Vec<LintDiagnostic> {
    if first_generated_marker(source).is_none() || has_lint_suppression_manifest(source) {
        return Vec::new();
    }

    source
        .lines()
        .enumerate()
        .filter_map(|(line_index, line)| {
            if is_inline_lint_suppression(line) {
                Some(LintDiagnostic {
                    path: path.to_path_buf(),
                    line: line_index + 1,
                    column: line.len() - line.trim_start().len() + 1,
                    rule_id: GENERATED_LINT_SUPPRESSION_RULE_ID,
                    rule_name: GENERATED_LINT_SUPPRESSION_RULE_NAME,
                    severity: Severity::Warning,
                    message: "generated lint suppressions must use structured manifest metadata",
                    fix_available: false,
                })
            } else {
                None
            }
        })
        .collect()
}

/// Builds diagnostics for generated files with unstructured skipped constructs.
pub(super) fn generated_skip_manifest_diagnostics(
    path: &Path,
    source: &str,
) -> Vec<LintDiagnostic> {
    if first_generated_marker(source).is_none() || has_skip_manifest(source) {
        return Vec::new();
    }

    source
        .lines()
        .enumerate()
        .filter_map(|(line_index, line)| {
            if is_unstructured_skip_note(line) {
                Some(LintDiagnostic {
                    path: path.to_path_buf(),
                    line: line_index + 1,
                    column: line.len() - line.trim_start().len() + 1,
                    rule_id: GENERATED_SKIP_MANIFEST_RULE_ID,
                    rule_name: GENERATED_SKIP_MANIFEST_RULE_NAME,
                    severity: Severity::Warning,
                    message:
                        "generated skipped constructs must use structured skip-manifest metadata",
                    fix_available: false,
                })
            } else {
                None
            }
        })
        .collect()
}

/// Returns the first generated marker location.
fn first_generated_marker(source: &str) -> Option<(usize, usize)> {
    source.lines().enumerate().find_map(|(line_index, line)| {
        if is_generated_marker(line) {
            Some((line_index, line.len() - line.trim_start().len() + 1))
        } else {
            None
        }
    })
}

/// Returns whether one source line marks generated content.
fn is_generated_marker(line: &str) -> bool {
    let lowered = line.to_ascii_lowercase();
    lowered.contains("@generated")
        || lowered.contains("generated by")
        || lowered.contains("do not edit")
        || lowered.contains("this file is generated")
}

/// Returns whether generated source records its source manifest.
fn has_generated_source_manifest(source: &str) -> bool {
    source.lines().any(|line| {
        let lowered = line.to_ascii_lowercase();
        lowered.contains("source-manifest:") || lowered.contains("generated-source:")
    })
}

/// Returns whether generated source records structured lint suppression data.
fn has_lint_suppression_manifest(source: &str) -> bool {
    source.lines().any(|line| {
        let lowered = line.to_ascii_lowercase();
        lowered.contains("lint-suppression-manifest:") || lowered.contains("lint-suppressions:")
    })
}

/// Returns whether generated source records structured skipped construct data.
fn has_skip_manifest(source: &str) -> bool {
    source.lines().any(|line| {
        let lowered = line.to_ascii_lowercase();
        lowered.contains("skip-manifest:")
            || lowered.contains("unsupported-manifest:")
            || lowered.contains("generated-skips:")
    })
}

/// Returns whether one line contains an inline lint suppression.
fn is_inline_lint_suppression(line: &str) -> bool {
    let lowered = line.to_ascii_lowercase();
    lowered.contains("lint-disable")
        || lowered.contains("terlan-lint-ignore")
        || lowered.contains("nolint")
        || lowered.contains("suppress lint")
}

/// Returns whether one generated line mentions skipped unsupported constructs.
fn is_unstructured_skip_note(line: &str) -> bool {
    let lowered = line.to_ascii_lowercase();
    lowered.contains("unsupported")
        || lowered.contains("skipped")
        || lowered.contains("not generated")
        || lowered.contains("not emitted")
}
