#!/usr/bin/env python3
"""Validate committed generated std.js bindings against pinned inputs.

Inputs:
- `std/js/manifests/std_js_dom_inputs.json`, the pinned TypeScript fixture
  input manifest.
- Committed generated `std.js` sources, interfaces, summaries, tests, and
  binding manifests. `.typi` summaries are intentionally excluded because
  `std/scripts/check_summary_drift.py` is the single authority for normalized
  committed summary artifacts.

Outputs:
- Exit status 0 with a compact success message when generated artifacts match.
- Exit status 1 with stable diagnostics when generation fails, an artifact is
  missing, or committed content differs from regenerated content.

Transformation:
- Runs `terlc bind js-dom` into a temporary directory and byte-compares every
  generated file against its committed repository counterpart.
"""

from __future__ import annotations

import filecmp
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUT_MANIFEST = Path("std/js/manifests/std_js_dom_inputs.json")


@dataclass(frozen=True)
class DriftDiagnostic:
    """One generated std.js drift diagnostic.

    Inputs:
    - `path`: repository-relative artifact path.
    - `message`: human-readable drift reason.

    Output:
    - Immutable diagnostic rendered by `format`.

    Transformation:
    - Keeps path and reason together so all drift checks report a stable,
      scan-friendly line format.
    """

    path: Path
    message: str

    def format(self) -> str:
        """Render this diagnostic for stderr output.

        Inputs:
        - `self`: one immutable diagnostic.

        Output:
        - Stable one-line diagnostic string.

        Transformation:
        - Converts the path to POSIX-style text and appends the drift message.
        """

        return f"{self.path.as_posix()}: {self.message}"


def run_generator(out_dir: Path) -> subprocess.CompletedProcess[str]:
    """Regenerate JS DOM bindings into a temporary output directory.

    Inputs:
    - `out_dir`: empty temporary destination directory.

    Output:
    - Completed `cargo run -p terlan_cli -- bind js-dom ...` process.

    Transformation:
    - Invokes the public compiler command so drift validation covers the same
      maintainer-facing generation path used to refresh committed artifacts.
    """

    return subprocess.run(
        [
            "cargo",
            "run",
            "-q",
            "-p",
            "terlan_cli",
            "--",
            "bind",
            "js-dom",
            "--manifest",
            INPUT_MANIFEST.as_posix(),
            "--out",
            str(out_dir),
        ],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def is_binding_artifact(path: Path) -> bool:
    """Return whether a generated file is owned by the binding drift check.

    Inputs:
    - `path`: generated path relative to the temporary output directory.

    Output:
    - `True` for generated binding sources, interfaces, tests, and manifests.
    - `False` for summary artifacts owned by the std summary drift checker.

    Transformation:
    - Keeps generated API-surface drift separate from normalized `.typi`
      summary drift so release preflight has one authority per artifact class.
    """

    return path.suffix not in {".typi", ".deps"}


def generated_files(out_dir: Path) -> list[Path]:
    """List generated std.js artifact paths relative to the temp output root.

    Inputs:
    - `out_dir`: generator output directory.

    Output:
    - Sorted repository-relative artifact paths generated by the command.

    Transformation:
    - Recursively walks regular files below the temp output directory and
      returns paths relative to that directory for stable committed-file
      comparison.
    """

    return sorted(
        relative
        for path in out_dir.rglob("*")
        if path.is_file()
        for relative in [path.relative_to(out_dir)]
        if is_binding_artifact(relative)
    )


def compare_generated_files(out_dir: Path) -> list[DriftDiagnostic]:
    """Compare regenerated std.js artifacts to committed files.

    Inputs:
    - `out_dir`: generator output directory containing regenerated artifacts.

    Output:
    - Diagnostics for missing or stale committed files.

    Transformation:
    - Byte-compares every generated file with the repository file at the same
      relative path. The generated set is authoritative for this drift check.
    """

    diagnostics: list[DriftDiagnostic] = []
    for relative in generated_files(out_dir):
        generated = out_dir / relative
        committed = ROOT / relative
        if not committed.is_file():
            diagnostics.append(DriftDiagnostic(relative, "missing committed generated artifact"))
        elif not filecmp.cmp(generated, committed, shallow=False):
            diagnostics.append(
                DriftDiagnostic(relative, "committed generated artifact is stale")
            )
    return diagnostics


def main() -> int:
    """Run generated std.js binding drift validation.

    Inputs:
    - Repository-local pinned TypeScript fixture manifest and generated outputs.

    Output:
    - Process exit code for Makefile/CI use.

    Transformation:
    - Regenerates JS DOM bindings into a temporary directory, compares them to
      committed artifacts, prints stable diagnostics, and deletes the temporary
      output automatically.
    """

    with tempfile.TemporaryDirectory(prefix="terlan-std-js-bindings-") as temp:
        out_dir = Path(temp)
        result = run_generator(out_dir)
        if result.returncode != 0:
            print("[std-js-bindings-drift] generation failed:", file=sys.stderr)
            print(result.stdout, file=sys.stderr, end="")
            print(result.stderr, file=sys.stderr, end="")
            return 1

        diagnostics = compare_generated_files(out_dir)
        if diagnostics:
            print("[std-js-bindings-drift] failures:", file=sys.stderr)
            for diagnostic in diagnostics:
                print(f"  - {diagnostic.format()}", file=sys.stderr)
            return 1

        print(
            f"[std-js-bindings-drift] {len(generated_files(out_dir))} generated artifacts match committed files."
        )
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
