[package]
name = "terlan-runtime-abi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
poll-io = ["dep:mio"]

[dependencies]
mio = { workspace = true, features = ["os-poll"], optional = true }

[lints]
workspace = true
