use std::fs;
use std::path::{Path, PathBuf};

use instant_acme::AccountCredentials;

use super::{is_acme_http01_token, load_certificate_chain, load_private_key, AcmeRuntimePlan};

/// Loads cached ACME account credentials.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
///
/// Output:
/// - `Ok(None)` when no account cache exists.
/// - `Ok(Some(AccountCredentials))` when the account cache is valid JSON.
/// - Stable `error[serve_tls]` diagnostic when the cache cannot be read or
///   decoded.
///
/// Transformation:
/// - Deserializes the opaque `instant-acme` account credential payload from
///   the deterministic project-local cache file without interpreting its
///   private fields.
pub(super) fn load_acme_account_credentials(
    plan: &AcmeRuntimePlan,
) -> Result<Option<AccountCredentials>, String> {
    let contents = match fs::read_to_string(&plan.account_credentials_path) {
        Ok(contents) => contents,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => {
            return Err(format!(
                "error[serve_tls]: failed to read ACME account credentials `{}`: {err}",
                plan.account_credentials_path.display()
            ));
        }
    };
    serde_json::from_str::<AccountCredentials>(&contents)
        .map(Some)
        .map_err(|err| {
            format!(
                "error[serve_tls]: failed to parse ACME account credentials `{}`: {err}",
                plan.account_credentials_path.display()
            )
        })
}

/// Stores ACME account credentials.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `credentials`: opaque credentials returned by `instant-acme`.
///
/// Output:
/// - `Ok(())` when credentials are durably written to the project cache.
///
/// Transformation:
/// - Serializes through `serde_json` and writes through a temporary file before
///   renaming into place, so interrupted issuance does not leave partial
///   account JSON at the runtime path.
pub(super) fn store_acme_account_credentials(
    plan: &AcmeRuntimePlan,
    credentials: &AccountCredentials,
) -> Result<(), String> {
    let contents = serde_json::to_string_pretty(credentials).map_err(|err| {
        format!("error[serve_tls]: failed to serialize ACME account credentials: {err}")
    })?;
    write_cache_file_atomically(&plan.account_credentials_path, contents.as_bytes())
}

/// Stores one ACME HTTP-01 challenge response.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `token`: ACME HTTP-01 challenge token.
/// - `key_authorization`: ACME key authorization body generated by
///   `instant-acme`.
///
/// Output:
/// - Path to the written challenge response file.
///
/// Transformation:
/// - Validates the token against the same URL-safe filename policy used by the
///   request handler, then writes the response under
///   `.terlan/tls/acme/http-01`.
pub(super) fn store_acme_http01_challenge(
    plan: &AcmeRuntimePlan,
    token: &str,
    key_authorization: &str,
) -> Result<PathBuf, String> {
    if !is_acme_http01_token(token) {
        return Err(format!(
            "error[serve_tls]: ACME HTTP-01 token `{token}` is invalid"
        ));
    }
    let path = plan.http01_challenge_dir.join(token);
    write_cache_file_atomically(&path, key_authorization.as_bytes())?;
    Ok(path)
}

/// Stores issued ACME certificate material.
///
/// Inputs:
/// - `plan`: normalized ACME runtime plan.
/// - `certificate_pem`: issued certificate chain PEM.
/// - `private_key_pem`: private key PEM used by the CSR.
///
/// Output:
/// - `Ok(())` when both runtime cache files are written and parseable by
///   `rustls`.
///
/// Transformation:
/// - Writes certificate/key to temporary paths, validates them through the same
///   PEM/rustls path used by serving, then atomically renames them into the
///   deterministic ACME cache.
pub(super) fn store_acme_certificate_cache(
    plan: &AcmeRuntimePlan,
    certificate_pem: &str,
    private_key_pem: &str,
) -> Result<(), String> {
    let cert_temp = temporary_cache_path(&plan.certificate_path);
    let key_temp = temporary_cache_path(&plan.private_key_path);
    write_cache_file_atomically(&cert_temp, certificate_pem.as_bytes())?;
    write_cache_file_atomically(&key_temp, private_key_pem.as_bytes())?;
    let certificates = load_certificate_chain(&cert_temp);
    let private_key = load_private_key(&key_temp);
    match (certificates, private_key) {
        (Ok(_), Ok(_)) => {
            rename_cache_file(&cert_temp, &plan.certificate_path)?;
            rename_cache_file(&key_temp, &plan.private_key_path)?;
            Ok(())
        }
        (Err(message), _) | (_, Err(message)) => {
            let _ = fs::remove_file(&cert_temp);
            let _ = fs::remove_file(&key_temp);
            Err(message)
        }
    }
}

/// Writes one cache file through a temporary path.
///
/// Inputs:
/// - `path`: final cache file path.
/// - `contents`: bytes to write.
///
/// Output:
/// - `Ok(())` when the file exists at `path`.
///
/// Transformation:
/// - Creates the parent directory, writes sibling temporary content, and then
///   renames over the final path to avoid partial cache files.
fn write_cache_file_atomically(path: &Path, contents: &[u8]) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| {
            format!(
                "error[serve_tls]: failed to create ACME cache directory `{}`: {err}",
                parent.display()
            )
        })?;
    }
    let temp_path = temporary_cache_path(path);
    fs::write(&temp_path, contents).map_err(|err| {
        format!(
            "error[serve_tls]: failed to write ACME cache file `{}`: {err}",
            temp_path.display()
        )
    })?;
    rename_cache_file(&temp_path, path)
}

/// Builds a sibling temporary path for one ACME cache file.
///
/// Inputs:
/// - `path`: final cache path.
///
/// Output:
/// - Temporary path with a process-local suffix.
///
/// Transformation:
/// - Keeps temporary files next to the destination so rename stays on the same
///   filesystem.
fn temporary_cache_path(path: &Path) -> PathBuf {
    let suffix = format!("tmp-{}", std::process::id());
    let extension = path.extension().and_then(|extension| extension.to_str());
    let temporary_extension = extension
        .map(|extension| format!("{extension}.{suffix}"))
        .unwrap_or(suffix);
    path.with_extension(temporary_extension)
}

/// Renames a temporary ACME cache file into place.
///
/// Inputs:
/// - `source`: temporary file path.
/// - `target`: final cache path.
///
/// Output:
/// - `Ok(())` when the target has replaced any previous cache file.
///
/// Transformation:
/// - Delegates to `std::fs::rename` and converts IO errors to stable serve TLS
///   diagnostics.
fn rename_cache_file(source: &Path, target: &Path) -> Result<(), String> {
    fs::rename(source, target).map_err(|err| {
        format!(
            "error[serve_tls]: failed to move ACME cache file `{}` to `{}`: {err}",
            source.display(),
            target.display()
        )
    })
}
