use super::*;
use crate::terlan_native::{json, postgres};
use crate::terlan_native_boundary::cancellation::NativeBoundaryCancellationToken;
use crate::terlan_native_boundary::resource::{ResourceError, ResourceValue};

/// Extracts a handle from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain a handle.
///
/// Output:
/// - `Some(handle)` when the reply is a handle success.
/// - `None` after asserting the reply had an unexpected shape.
///
/// Transformation:
/// - Pattern-matches the stable reply term without unwrap/expect.
fn handle_reply(reply: NativeBoundaryReplyTerm) -> Option<NativeBoundaryHandle> {
    let NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Handle { id, generation }) = reply else {
        return None;
    };
    Some(NativeBoundaryHandle { id, generation })
}

/// Builds a handle term from a runtime handle.
///
/// Inputs:
/// - `handle`: opaque runtime handle.
///
/// Output:
/// - Stable term that carries the handle id and generation.
///
/// Transformation:
/// - Copies handle identity into the term shape expected by runtime calls.
fn handle_term(handle: NativeBoundaryHandle) -> NativeBoundaryTerm {
    NativeBoundaryTerm::Handle {
        id: handle.id,
        generation: handle.generation,
    }
}

/// Verifies cancellation is checked after admission and before adapter entry.
#[test]
fn runtime_policy_dispatch_observes_cooperative_cancellation() {
    let mut runtime = NativeBoundaryRuntime::new();
    let cancellation = NativeBoundaryCancellationToken::new();
    cancellation.cancel();

    let reply = runtime.call_for_process_with_policy_and_cancellation(
        7,
        &["postgres"],
        &[crate::terlan_native_boundary::metadata::NativeBoundaryWorkerClass::ResourceOwning],
        "std.db.postgres.connect",
        &[NativeBoundaryTerm::PostgresConfig(postgres::Config::new(
            "postgres://localhost/terlan",
        ))],
        &cancellation,
    );

    let error = crate::terlan_native_boundary::error::error_for(
        crate::terlan_native_boundary::error::ErrorKind::Cancelled,
    );
    assert_eq!(
        reply,
        NativeBoundaryReplyTerm::Error {
            code: error.code.to_string(),
            message: error.message.to_string(),
            offset: 0,
        }
    );
}

fn expected_postgres_unreachable_error() -> NativeBoundaryReplyTerm {
    NativeBoundaryReplyTerm::Error {
        code: String::from("postgres.vm_driver_unavailable"),
        message: String::from("Postgres execution requires the VM-owned Postgres I/O driver."),
        offset: 0,
    }
}

/// Extracts a text value from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain text.
///
/// Output:
/// - `Some(text)` when the reply is a text success.
/// - `None` for any other reply shape.
///
/// Transformation:
/// - Pattern-matches the stable reply term without panicking.
fn text_reply(reply: NativeBoundaryReplyTerm) -> Option<String> {
    let NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(value)) = reply else {
        return None;
    };
    Some(value)
}

/// Extracts an optional handle from a successful reply term.
///
/// Inputs:
/// - `reply`: runtime reply expected to contain an optional handle.
///
/// Output:
/// - `Some(handle)` when the reply is `OptionalHandle(Some(_))`.
/// - `None` for missing rows or unexpected reply shapes.
///
/// Transformation:
/// - Uses the same term shape generated by resource-backed optional results.
fn some_handle_reply(reply: NativeBoundaryReplyTerm) -> Option<NativeBoundaryHandle> {
    let NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::OptionalHandle(Some(handle))) = reply
    else {
        return None;
    };
    Some(handle)
}

/// Reads the optional live Postgres test URL.
///
/// Inputs:
/// - `test_name`: name used in the skip diagnostic.
///
/// Output:
/// - `Some(url)` when `TERLAN_TEST_POSTGRES_URL` is configured.
/// - `None` when the live handler test should be skipped.
///
/// Transformation:
/// - Reads only the process environment and emits a skip line for ordinary
///   unit test runs without a database.
fn live_postgres_url(test_name: &str) -> Option<String> {
    match std::env::var("TERLAN_TEST_POSTGRES_URL") {
        Ok(url) => Some(url),
        Err(_) => {
            eprintln!("skipping {test_name}; TERLAN_TEST_POSTGRES_URL is not set");
            None
        }
    }
}

/// Verifies JSON can execute through the term runtime path.
///
/// Inputs:
/// - JSON text, object key, and operation ids.
///
/// Output:
/// - Test passes when parse/get/as-string returns the expected text.
///
/// Transformation:
/// - Exercises term decoding, resource-backed dispatch, opaque handle
///   storage, and reply encoding together.
#[test]
fn runtime_executes_json_operations_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(root) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from(r#"{"name":"Ada"}"#))],
    )) else {
        return;
    };
    let Some(name) = handle_reply(runtime.call(
        "std.data.json.get",
        &[
            NativeBoundaryTerm::Handle {
                id: root.id,
                generation: root.generation,
            },
            NativeBoundaryTerm::Text(String::from("name")),
        ],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.data.json.as_string",
            &[NativeBoundaryTerm::Handle {
                id: name.id,
                generation: name.generation,
            }],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("Ada")))
    );
}

/// Verifies Base64 can execute through the term runtime path.
///
/// Inputs:
/// - Text operation argument.
///
/// Output:
/// - Test passes when encode returns the expected Base64 text.
///
/// Transformation:
/// - Exercises primitive-only NativeBoundary dispatch without resource handles.
#[test]
fn runtime_executes_base64_operations_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();

    assert_eq!(
        runtime.call(
            "std.encoding.base64.encode",
            &[NativeBoundaryTerm::Text(String::from("hello"))],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("aGVsbG8=")))
    );
}

/// Verifies path operations can return optional handle terms.
///
/// Inputs:
/// - Path text with a parent component.
///
/// Output:
/// - Test passes when parent returns `OptionalHandle(Some(_))`.
///
/// Transformation:
/// - Exercises optional opaque resource results through the runtime term
///   boundary.
#[test]
fn runtime_executes_path_optional_handle_operations_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(path) = handle_reply(runtime.call(
        "std.io.path.from_string",
        &[NativeBoundaryTerm::Text(String::from("src/main.terl"))],
    )) else {
        return;
    };

    let parent = runtime.call(
        "std.io.path.parent",
        &[NativeBoundaryTerm::Handle {
            id: path.id,
            generation: path.generation,
        }],
    );

    assert!(matches!(
        parent,
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::OptionalHandle(Some(_)))
    ));
}

/// Verifies HTTP cookie jars execute through the term runtime path.
///
/// Inputs:
/// - A server-owned request resource with one parsed incoming cookie.
///
/// Output:
/// - Test passes when the runtime creates a cookie jar handle, reads an
///   incoming cookie, and records cookie set/delete mutations as `Unit`
///   operations.
///
/// Transformation:
/// - Exercises the bridge path a server adapter will use: register request
///   state, call `Request.cookies`, then mutate the returned jar by handle.
#[test]
fn runtime_executes_http_cookie_jar_operations_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();
    let request = http::Request::from_parts_with_metadata(
        "GET",
        "/profile",
        "",
        Vec::new(),
        Vec::new(),
        vec![("theme".to_string(), "dark".to_string())],
    );
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };
    let Some(jar) = handle_reply(runtime.call(
        "std.http.request.cookies",
        &[NativeBoundaryTerm::Handle {
            id: request.id,
            generation: request.generation,
        }],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.http.cookies.get",
            &[
                NativeBoundaryTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                NativeBoundaryTerm::Text(String::from("theme")),
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::OptionalText(Some(String::from("dark"))))
    );
    assert_eq!(
        runtime.call(
            "std.http.cookies.set",
            &[
                NativeBoundaryTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                NativeBoundaryTerm::Text(String::from("session")),
                NativeBoundaryTerm::Text(String::from("abc123")),
                NativeBoundaryTerm::Text(String::from("/")),
                NativeBoundaryTerm::Bool(true),
                NativeBoundaryTerm::Bool(false),
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );
    assert_eq!(
        runtime.call(
            "std.http.cookies.delete",
            &[
                NativeBoundaryTerm::Handle {
                    id: jar.id,
                    generation: jar.generation,
                },
                NativeBoundaryTerm::Text(String::from("theme")),
                NativeBoundaryTerm::Text(String::from("/")),
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );
    assert_eq!(
        runtime.http_cookie_mutations(jar),
        Ok(vec![
            String::from("session=abc123; HttpOnly; Path=/"),
            String::from("theme=; Path=/; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT")
        ])
    );
}

/// Verifies HTTP response resources can be returned to a server adapter.
///
/// Inputs:
/// - Response text and status supplied through stable runtime terms.
///
/// Output:
/// - Test passes when `std.http.response.text` returns a handle that can be
///   read back as a portable HTTP response snapshot.
///
/// Transformation:
/// - Exercises the last step of handler execution without requiring any live
///   database state.
#[test]
fn runtime_returns_http_response_resources_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(response) = handle_reply(runtime.call(
        "std.http.response.text",
        &[
            NativeBoundaryTerm::Text(String::from("ok")),
            NativeBoundaryTerm::Int(202),
        ],
    )) else {
        return;
    };
    let Some(response) = runtime.http_response(response).ok() else {
        return;
    };

    assert_eq!(response.status_code(), 202);
    assert_eq!(response.content_type(), "text/plain; charset=utf-8");
    assert_eq!(response.body(), "ok");
}

/// Verifies response extraction rejects non-response resource handles.
///
/// Inputs:
/// - A request handle registered in the runtime.
///
/// Output:
/// - Test passes when extracting it as a response returns `resource.kind`.
///
/// Transformation:
/// - Exercises the server-side response handle validation failure path.
#[test]
fn runtime_rejects_non_response_handles_as_handler_results() {
    let mut runtime = NativeBoundaryRuntime::new();
    let request = http::Request::from_parts("GET", "/", "");
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };
    let error = runtime
        .http_response(request)
        .err()
        .unwrap_or_else(|| ResourceError::new("missing", "missing"));

    assert_eq!(error.code(), "resource.kind");
}

/// Verifies an HTTP handler-shaped runtime flow can call Postgres and respond.
///
/// Inputs:
/// - `TERLAN_TEST_POSTGRES_URL`: optional live Postgres URL supplied by an
///   opt-in integration gate.
///
/// Output:
/// - Test is skipped when no URL is configured.
/// - Test passes when one runtime owns request state, a live Postgres pool,
///   the queried row, and the final HTTP response resource.
///
/// Transformation:
/// - Simulates the server bridge sequence for a Terlan HTTP handler: register
///   the request, read request data through `std.http.request.*`, connect and
///   query through `std.db.postgres.*`, then return `std.http.response.text`.
#[test]
fn runtime_executes_full_cycle_http_postgres_handler_when_configured() {
    let Some(url) = live_postgres_url("live HTTP handler Postgres runtime test") else {
        return;
    };
    let mut runtime = NativeBoundaryRuntime::new();
    let request = http::Request::from_parts_with_metadata(
        "GET",
        "/db-health",
        "",
        Vec::new(),
        vec![(String::from("check"), String::from("postgres"))],
        Vec::new(),
    );
    let Some(request) = runtime.register_http_request(request).ok() else {
        return;
    };

    let Some(path) = text_reply(runtime.call("std.http.request.path", &[handle_term(request)]))
    else {
        return;
    };
    assert_eq!(path, "/db-health");

    let Some(path_json) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("\"/db-health\""))],
    )) else {
        return;
    };
    let config = postgres::Config::new(url)
        .with_pool_limits(1, 2)
        .with_timeouts(1_000, 1_000);
    let Some(pool) = handle_reply(runtime.call(
        "std.db.postgres.connect",
        &[NativeBoundaryTerm::PostgresConfig(config)],
    )) else {
        return;
    };
    let Some(row) = some_handle_reply(runtime.call(
        "std.db.postgres.query_one",
        &[
            handle_term(pool),
            NativeBoundaryTerm::Text(String::from(
                "SELECT $1::TEXT AS request_path, 'postgres-ok'::TEXT AS status",
            )),
            NativeBoundaryTerm::List(vec![handle_term(path_json)]),
        ],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.db.postgres.string",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("request_path"))
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("/db-health")))
    );
    let Some(status) = text_reply(runtime.call(
        "std.db.postgres.string",
        &[
            handle_term(row),
            NativeBoundaryTerm::Text(String::from("status")),
        ],
    )) else {
        return;
    };
    let Some(response) = handle_reply(runtime.call(
        "std.http.response.text",
        &[
            NativeBoundaryTerm::Text(format!("{path}:{status}")),
            NativeBoundaryTerm::Int(200),
        ],
    )) else {
        return;
    };
    let Some(response) = runtime.http_response(response).ok() else {
        return;
    };

    assert_eq!(response.status_code(), 200);
    assert_eq!(response.content_type(), "text/plain; charset=utf-8");
    assert_eq!(response.body(), "/db-health:postgres-ok");
}

/// Verifies disposed handles are rejected by later runtime calls.
///
/// Inputs:
/// - JSON parse output handle disposed before a second call.
///
/// Output:
/// - Test passes when the later operation returns `resource.stale_handle`.
///
/// Transformation:
/// - Exercises deterministic cleanup and stale-handle rejection through the
///   term runtime boundary.
#[test]
fn runtime_rejects_disposed_handles_through_terms() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(root) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("null"))],
    )) else {
        return;
    };
    assert_eq!(
        runtime.dispose(root),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );

    assert_eq!(
        runtime.call(
            "std.data.json.is_null",
            &[NativeBoundaryTerm::Handle {
                id: root.id,
                generation: root.generation,
            }],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.stale_handle"),
            message: String::from("NativeBoundary resource handle 1 generation 1 is not live."),
            offset: 0,
        }
    );
}

/// Verifies duplicate disposal is reported as a stable stale-handle failure.
///
/// Inputs:
/// - JSON parse output handle disposed twice.
///
/// Output:
/// - First disposal succeeds.
/// - Second disposal returns `resource.stale_handle`.
///
/// Transformation:
/// - Exercises cleanup race behavior without exposing adapter-owned resource
///   values or panicking on duplicate cleanup.
#[test]
fn runtime_rejects_duplicate_dispose_as_stale_handle() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(root) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("null"))],
    )) else {
        return;
    };

    assert_eq!(
        runtime.dispose(root),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );
    assert_eq!(
        runtime.dispose(root),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.stale_handle"),
            message: String::from("NativeBoundary resource handle 1 generation 1 is not live."),
            offset: 0,
        }
    );
}

/// Verifies one VM process cannot dispatch with another process's handle.
#[test]
fn runtime_rejects_cross_process_resource_access() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(root) = handle_reply(runtime.call_for_process(
        7,
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("null"))],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call_for_process(8, "std.data.json.is_null", &[handle_term(root)],),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.owner"),
            message: String::from(
                "NativeBoundary resource handle 1 belongs to process 7, not process 8."
            ),
            offset: 0,
        }
    );
    assert_eq!(
        runtime.call_for_process(7, "std.data.json.is_null", &[handle_term(root)]),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Bool(true))
    );
}

/// Verifies one VM process cannot dispose another process's handle.
#[test]
fn runtime_rejects_cross_process_resource_disposal() {
    let mut runtime = NativeBoundaryRuntime::new();
    let Some(root) = handle_reply(runtime.call_for_process(
        7,
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("null"))],
    )) else {
        return;
    };

    assert_eq!(
        runtime.dispose_for_process(8, root),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.owner"),
            message: String::from(
                "NativeBoundary resource handle 1 belongs to process 7, not process 8."
            ),
            offset: 0,
        }
    );
    assert_eq!(
        runtime.dispose_for_process(7, root),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );
}

/// Verifies process-scoped Postgres calls require the manifest capability.
#[test]
fn runtime_enforces_postgres_capability_before_adapter_execution() {
    let mut runtime = NativeBoundaryRuntime::new();
    let config = NativeBoundaryTerm::PostgresConfig(postgres::Config::new("sqlite://local.db"));

    for granted_capabilities in [&[][..], &["filesystem.path"][..]] {
        assert_eq!(
            runtime.call_for_process_with_capabilities(
                7,
                granted_capabilities,
                "std.db.postgres.connect",
                std::slice::from_ref(&config),
            ),
            NativeBoundaryReplyTerm::Error {
                code: String::from("native_boundary.capability_denied"),
                message: String::from(
                    "NativeBoundary operation `std.db.postgres.connect` requires capability `postgres`."
                ),
                offset: 0,
            }
        );
    }

    assert_eq!(
        runtime.call_for_process_with_capabilities(
            7,
            &["postgres"],
            "std.db.postgres.connect",
            &[config],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("native_boundary.scheduler_denied"),
            message: String::from(
                "NativeBoundary operation `std.db.postgres.connect` requires `resource-owning` scheduler admission."
            ),
            offset: 0,
        }
    );

    assert_eq!(
        runtime.call_for_process_with_policy(
            7,
            &["postgres"],
            &[NativeBoundaryWorkerClass::ResourceOwning],
            "std.db.postgres.connect",
            &[NativeBoundaryTerm::PostgresConfig(postgres::Config::new(
                "sqlite://local.db",
            ))],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("postgres.invalid_url"),
            message: String::from("Postgres connection URL scheme `sqlite` is not supported."),
            offset: 0,
        }
    );
}

/// Verifies malformed term payloads return typed dispatch errors.
///
/// Inputs:
/// - `std.data.json.as_string` called with a text term instead of a JSON
///   resource handle.
///
/// Output:
/// - Stable `dispatch.type` error with no Rust panic or backend exception.
///
/// Transformation:
/// - Exercises malformed NativeBoundary payload rejection at the term runtime
///   boundary.
#[test]
fn runtime_rejects_malformed_payload_with_typed_error() {
    let mut runtime = NativeBoundaryRuntime::new();

    assert_eq!(
        runtime.call(
            "std.data.json.as_string",
            &[NativeBoundaryTerm::Text(String::from("not-a-handle"))],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("dispatch.type"),
            message: String::from("Operation `std.data.json.as_string` argument 0 must be `Json`."),
            offset: 0,
        }
    );
}

/// Verifies Postgres resources are disposed through VM-owned runtime handles.
///
/// Inputs:
/// - Disconnected Postgres pool fixture and synthetic row fixture registered
///   as NativeBoundary resources.
///
/// Output:
/// - Pool and row handles are live before disposal.
/// - Both handles become stable stale handles after disposal.
///
/// Transformation:
/// - Exercises Postgres-specific resource cleanup without opening a live
///   database connection or leaking Rust adapter values through VM terms.
#[test]
fn runtime_disposes_postgres_pool_and_row_resources() {
    let mut runtime = NativeBoundaryRuntime::new();
    let pool = runtime
        .resources
        .insert(ResourceValue::PostgresPool(
            postgres::test_support::disconnected_pool("postgres://localhost/terlan"),
        ))
        .expect("pool handle should allocate");
    let mut row = postgres::Row::new();
    row.put_string("status", "ok");
    let row = runtime
        .resources
        .insert(ResourceValue::PostgresRow(row))
        .expect("row handle should allocate");

    assert_eq!(
        runtime.call(
            "std.db.postgres.string",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("status"))
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("ok")))
    );
    assert_eq!(
        runtime.dispose(pool),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );
    assert_eq!(
        runtime.dispose(row),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Unit)
    );

    assert_eq!(
        runtime.call(
            "std.db.postgres.execute",
            &[
                handle_term(pool),
                NativeBoundaryTerm::Text(String::from("SELECT 1")),
                NativeBoundaryTerm::List(Vec::new()),
            ],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.stale_handle"),
            message: String::from("NativeBoundary resource handle 1 generation 1 is not live."),
            offset: 0,
        }
    );
    assert_eq!(
        runtime.call(
            "std.db.postgres.string",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("status"))
            ],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.stale_handle"),
            message: String::from("NativeBoundary resource handle 2 generation 1 is not live."),
            offset: 0,
        }
    );
}

/// Verifies Postgres NativeBoundary calls return typed runtime errors.
///
/// Inputs:
/// - Unsupported Postgres config URL.
/// - JSON resource handle passed where a Postgres pool handle is required.
///
/// Output:
/// - Invalid config returns the stable Postgres adapter error.
/// - Wrong resource kind returns the stable NativeBoundary kind error.
///
/// Transformation:
/// - Exercises deterministic Postgres error paths through the VM runtime
///   boundary without opening a database connection.
#[test]
fn runtime_returns_postgres_typed_errors_without_live_database() {
    let mut runtime = NativeBoundaryRuntime::new();

    assert_eq!(
        runtime.call(
            "std.db.postgres.connect",
            &[NativeBoundaryTerm::PostgresConfig(postgres::Config::new(
                "sqlite://local.db",
            ))],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("postgres.invalid_url"),
            message: String::from("Postgres connection URL scheme `sqlite` is not supported."),
            offset: 0,
        }
    );

    let Some(json_handle) = handle_reply(runtime.call(
        "std.data.json.parse",
        &[NativeBoundaryTerm::Text(String::from("null"))],
    )) else {
        return;
    };

    assert_eq!(
        runtime.call(
            "std.db.postgres.query_one",
            &[
                handle_term(json_handle),
                NativeBoundaryTerm::Text(String::from("SELECT 1")),
                NativeBoundaryTerm::List(Vec::new()),
            ],
        ),
        NativeBoundaryReplyTerm::Error {
            code: String::from("resource.kind"),
            message: String::from(
                "NativeBoundary resource handle 1 is Json, expected PostgresPool.",
            ),
            offset: 0,
        }
    );
}

/// Verifies Postgres SQL operations reject empty SQL through the VM boundary.
///
/// Inputs:
/// - Disconnected Postgres pool resource.
/// - Whitespace SQL passed to query, query-one, and execute.
///
/// Output:
/// - Each operation returns stable `postgres.sql.empty` before any driver or
///   socket checkout path.
///
/// Transformation:
/// - Exercises the VM NativeBoundary transport guard for all query-shaped
///   Postgres operations without requiring a live database.
#[test]
fn runtime_rejects_postgres_empty_sql_before_driver_dispatch() {
    let mut runtime = NativeBoundaryRuntime::new();
    let pool = runtime
        .resources
        .insert(ResourceValue::PostgresPool(
            postgres::test_support::disconnected_pool("postgres://localhost/terlan"),
        ))
        .expect("pool handle should allocate");
    let args = |sql: &str| {
        vec![
            handle_term(pool),
            NativeBoundaryTerm::Text(String::from(sql)),
            NativeBoundaryTerm::List(Vec::new()),
        ]
    };

    for operation in [
        "std.db.postgres.query",
        "std.db.postgres.query_one",
        "std.db.postgres.execute",
    ] {
        assert_eq!(
            runtime.call(operation, &args(" \n\t ")),
            NativeBoundaryReplyTerm::Error {
                code: String::from("postgres.sql.empty"),
                message: String::from("Postgres SQL text must not be empty."),
                offset: 0,
            },
            "{operation} should reject empty SQL before driver dispatch",
        );
    }
}

/// Verifies Postgres SQL operations reach the adapter through VM dispatch.
///
/// Inputs:
/// - Disconnected Postgres pool resource.
/// - Non-empty SQL passed to query, query-one, and execute.
///
/// Output:
/// - Each operation returns the stable unreachable-adapter error for the
///   current feature set, proving the call passed VM resource decoding and
///   entered the maintained Postgres adapter path.
///
/// Transformation:
/// - Exercises query-shaped NativeBoundary dispatch without a live database by
///   using the adapter's disconnected pool fixture.
#[test]
fn runtime_dispatches_postgres_sql_operations_to_adapter() {
    let mut runtime = NativeBoundaryRuntime::new();
    let pool = runtime
        .resources
        .insert(ResourceValue::PostgresPool(
            postgres::test_support::disconnected_pool("postgres://localhost/terlan"),
        ))
        .expect("pool handle should allocate");
    let args = |sql: &str| {
        vec![
            handle_term(pool),
            NativeBoundaryTerm::Text(String::from(sql)),
            NativeBoundaryTerm::List(Vec::new()),
        ]
    };

    for operation in [
        "std.db.postgres.query",
        "std.db.postgres.query_one",
        "std.db.postgres.execute",
    ] {
        assert_eq!(
            runtime.call(operation, &args("SELECT 1")),
            expected_postgres_unreachable_error(),
            "{operation} should reach the maintained Postgres adapter",
        );
    }
}

/// Verifies Postgres row accessors decode through VM NativeBoundary handles.
///
/// Inputs:
/// - Synthetic Postgres row resource with string, integer, boolean, and JSON
///   columns.
///
/// Output:
/// - Primitive column accessors return VM terms.
/// - JSON column accessor returns a JSON resource handle that can be decoded by
///   the JSON NativeBoundary adapter.
///
/// Transformation:
/// - Exercises Postgres row decoding through the same resource handle surface
///   used by live query results without requiring a database.
#[test]
fn runtime_decodes_postgres_row_columns_through_handles() {
    let mut runtime = NativeBoundaryRuntime::new();
    let mut row = postgres::Row::new();
    row.put_string("name", "Ada");
    row.put_int("age", 42);
    row.put_bool("active", true);
    row.put_json("meta", json::string("ok"));
    let row = runtime
        .resources
        .insert(ResourceValue::PostgresRow(row))
        .expect("row handle should allocate");

    assert_eq!(
        runtime.call(
            "std.db.postgres.string",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("name"))
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("Ada")))
    );
    assert_eq!(
        runtime.call(
            "std.db.postgres.int",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("age"))
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Int(42))
    );
    assert_eq!(
        runtime.call(
            "std.db.postgres.bool",
            &[
                handle_term(row),
                NativeBoundaryTerm::Text(String::from("active"))
            ],
        ),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Bool(true))
    );
    let Some(meta) = handle_reply(runtime.call(
        "std.db.postgres.json",
        &[
            handle_term(row),
            NativeBoundaryTerm::Text(String::from("meta")),
        ],
    )) else {
        return;
    };
    assert_eq!(
        runtime.call("std.data.json.as_string", &[handle_term(meta)]),
        NativeBoundaryReplyTerm::Ok(NativeBoundaryTerm::Text(String::from("ok")))
    );
}
