use std::path::Path;

use super::lint_source;

/// Verifies generated files without source manifests emit a stable diagnostic.
#[test]
fn lint_reports_generated_file_missing_source_manifest() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * Generated by terlc bind.
 */
module generated.Sample.
"#,
    );

    let rendered = diagnostics
        .iter()
        .map(super::super::render_diagnostic)
        .collect::<Vec<_>>()
        .join("\n");
    assert!(rendered.contains("Generated.terl:3:2"));
    assert!(rendered.contains("warning[TL0804:interop.generated-source-manifest]"));
    assert!(rendered.contains("generated source must include source-manifest metadata"));
}

/// Verifies generated files with explicit source manifests stay accepted.
#[test]
fn lint_accepts_generated_file_with_source_manifest() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * source-manifest: typescript:lib.dom.d.ts#Window
 * Generated by terlc bind.
 */
module generated.Sample.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0804"),
        "generated files with source manifests must be accepted: {diagnostics:?}"
    );
}

/// Verifies ordinary docs about generated values do not mark the file generated.
#[test]
fn lint_accepts_non_generated_file_mentioning_generated_values() {
    let diagnostics = lint_source(
        Path::new("Sample.terl"),
        r#"
module sample.

/**
 * Validates generated values.
 */
pub value(): Int ->
    1.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0804"),
        "ordinary source docs must not require generated source manifests: {diagnostics:?}"
    );
}

/// Verifies generated files cannot hide lint suppressions in comments.
#[test]
fn lint_reports_generated_file_inline_lint_suppression() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * source-manifest: typescript:lib.dom.d.ts#Window
 * lint-disable TL0006
 */
module generated.Sample.
"#,
    );

    let rendered = diagnostics
        .iter()
        .map(super::super::render_diagnostic)
        .collect::<Vec<_>>()
        .join("\n");
    assert!(rendered.contains("Generated.terl:5:2"));
    assert!(rendered.contains("warning[TL0805:interop.generated-lint-suppression]"));
    assert!(rendered.contains("generated lint suppressions must use structured manifest metadata"));
}

/// Verifies generated lint suppression manifests are accepted.
#[test]
fn lint_accepts_generated_file_lint_suppression_manifest() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * source-manifest: typescript:lib.dom.d.ts#Window
 * lint-suppression-manifest: generated-bindings/lint.json
 * lint-disable TL0006
 */
module generated.Sample.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0805"),
        "structured generated suppression manifests must be accepted: {diagnostics:?}"
    );
}

/// Verifies handwritten source suppression comments are outside this rule.
#[test]
fn lint_accepts_non_generated_inline_lint_suppression_text() {
    let diagnostics = lint_source(
        Path::new("Sample.terl"),
        r#"
module sample.

// lint-disable TL0006 is only blocked in generated source by this rule.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0805"),
        "non-generated suppression comments are outside generated-code lint: {diagnostics:?}"
    );
}

/// Verifies generated skipped constructs require structured skip manifests.
#[test]
fn lint_reports_generated_file_unstructured_skip_note() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * source-manifest: typescript:lib.dom.d.ts#Window
 * skipped unsupported mapped type WindowProxy.
 */
module generated.Sample.
"#,
    );

    let rendered = diagnostics
        .iter()
        .map(super::super::render_diagnostic)
        .collect::<Vec<_>>()
        .join("\n");
    assert!(rendered.contains("Generated.terl:5:2"));
    assert!(rendered.contains("warning[TL0806:interop.generated-skip-manifest]"));
    assert!(rendered.contains("generated skipped constructs must use structured skip-manifest"));
}

/// Verifies generated skip manifests make skipped construct notes auditable.
#[test]
fn lint_accepts_generated_file_skip_manifest() {
    let diagnostics = lint_source(
        Path::new("Generated.terl"),
        r#"
/**
 * @generated
 * source-manifest: typescript:lib.dom.d.ts#Window
 * skip-manifest: generated-bindings/skips.json
 * skipped unsupported mapped type WindowProxy.
 */
module generated.Sample.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0806"),
        "structured generated skip manifests must be accepted: {diagnostics:?}"
    );
}

/// Verifies handwritten unsupported notes are outside generated-code skip lint.
#[test]
fn lint_accepts_non_generated_unsupported_notes() {
    let diagnostics = lint_source(
        Path::new("Sample.terl"),
        r#"
module sample.

// unsupported values are documented by handwritten diagnostics elsewhere.
"#,
    );

    assert!(
        diagnostics
            .iter()
            .all(|diagnostic| diagnostic.rule_id != "TL0806"),
        "non-generated unsupported notes are outside generated skip lint: {diagnostics:?}"
    );
}
