[package]
name = "terlan-crypto-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
sha2.workspace = true
rustls = { workspace = true, features = ["ring", "std"] }
terlan-runtime-abi.workspace = true
