use std::io::{self, BufRead, Write};
use std::process::ExitCode;

use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use terlan_safenative::runtime::SafeNativeRuntime;
use terlan_safenative::term::{SafeNativeReplyTerm, SafeNativeTerm};

/// Executes the private generic SafeNative runtime helper.
///
/// Inputs:
/// - `args`: no public arguments are accepted.
///
/// Output:
/// - Exit success while serving generated BEAM SafeNative requests on
///   stdin/stdout.
/// - Exit failure for malformed startup only.
///
/// Transformation:
/// - Owns one resource-backed SafeNative runtime and speaks the line protocol
///   generated by `emit-native-metadata` Erlang stubs.
pub(crate) fn run(args: &[String]) -> ExitCode {
    if !args.is_empty() {
        eprintln!("terlc __safe-native-runtime does not accept arguments");
        return ExitCode::from(2);
    }
    run_loop(io::stdin().lock(), io::stdout())
}

/// Serves SafeNative requests from a line-oriented stream.
///
/// Inputs: readable request stream and writable response stream.
/// Output: success when input ends or output closes.
/// Transformation: owns one runtime instance and converts each protocol line
/// into one encoded response line.
fn run_loop(input: impl BufRead, mut output: impl Write) -> ExitCode {
    let mut runtime = SafeNativeRuntime::new();
    for line in input.lines() {
        let response = match line {
            Ok(line) => execute_line(&mut runtime, line.trim_end()),
            Err(error) => error_response(
                "safe_native_runtime_read_error",
                &format!("failed to read SafeNative request: {error}"),
            ),
        };
        if writeln!(output, "{response}").is_err() {
            return ExitCode::SUCCESS;
        }
        let _ = output.flush();
    }
    ExitCode::SUCCESS
}

/// Executes one SafeNative protocol line.
///
/// Inputs: mutable runtime and one trimmed request line.
/// Output: encoded success or error response.
/// Transformation: parses `call` requests, decodes arguments, dispatches to
/// the runtime, and encodes the reply.
fn execute_line(runtime: &mut SafeNativeRuntime, line: &str) -> String {
    let mut parts = line.split_whitespace();
    let Some(command) = parts.next() else {
        return error_response("safe_native_empty_command", "empty SafeNative command");
    };
    match command {
        "call" => {
            let Some(_request_id) = parts.next() else {
                return error_response("safe_native_missing_request", "missing request id");
            };
            let Some(operation) = parts.next().and_then(decode_text) else {
                return error_response("safe_native_missing_operation", "missing operation");
            };
            let args = match parts.map(decode_arg).collect::<Result<Vec<_>, _>>() {
                Ok(args) => args,
                Err(message) => return message,
            };
            encode_reply(&operation, runtime.call(&operation, &args))
        }
        other => error_response(
            "safe_native_unknown_command",
            &format!("unknown SafeNative command `{other}`"),
        ),
    }
}

/// Decodes one SafeNative argument token.
///
/// Inputs: protocol token with a type prefix.
/// Output: decoded runtime term or encoded error response string.
/// Transformation: accepts string, integer, handle, and string-list encodings.
fn decode_arg(value: &str) -> Result<SafeNativeTerm, String> {
    if let Some(encoded) = value.strip_prefix("s:") {
        return decode_text(encoded)
            .map(SafeNativeTerm::Text)
            .ok_or_else(|| error_response("safe_native_bad_string", "invalid string argument"));
    }
    if let Some(encoded) = value.strip_prefix("i:") {
        return encoded
            .parse::<i64>()
            .map(SafeNativeTerm::Int)
            .map_err(|err| {
                error_response(
                    "safe_native_bad_int",
                    &format!("invalid integer argument: {err}"),
                )
            });
    }
    if let Some(encoded) = value.strip_prefix("h:") {
        let mut parts = encoded.splitn(3, ':');
        let id = parts
            .next()
            .and_then(|text| text.parse::<u64>().ok())
            .ok_or_else(|| error_response("safe_native_bad_handle", "invalid handle id"))?;
        let generation = parts
            .next()
            .and_then(|text| text.parse::<u64>().ok())
            .ok_or_else(|| error_response("safe_native_bad_handle", "invalid handle generation"))?;
        return Ok(SafeNativeTerm::Handle { id, generation });
    }
    if let Some(encoded) = value.strip_prefix("ls:") {
        if encoded.is_empty() {
            return Ok(SafeNativeTerm::List(Vec::new()));
        }
        let values = encoded
            .split(',')
            .map(|part| {
                decode_text(part)
                    .map(SafeNativeTerm::Text)
                    .ok_or_else(|| error_response("safe_native_bad_list", "invalid list item"))
            })
            .collect::<Result<Vec<_>, _>>()?;
        return Ok(SafeNativeTerm::List(values));
    }
    Err(error_response(
        "safe_native_unsupported_arg",
        "unsupported SafeNative argument encoding",
    ))
}

/// Decodes base64 text used by the SafeNative line protocol.
///
/// Inputs: base64 encoded UTF-8 payload.
/// Output: decoded string when valid.
/// Transformation: decodes base64 bytes and validates UTF-8.
fn decode_text(value: &str) -> Option<String> {
    let bytes = STANDARD.decode(value).ok()?;
    String::from_utf8(bytes).ok()
}

/// Encodes a SafeNative runtime reply.
///
/// Inputs: operation id and runtime reply term.
/// Output: line-protocol response string.
/// Transformation: preserves runtime errors and delegates successful payloads
/// to operation-aware success encoding.
fn encode_reply(operation: &str, reply: SafeNativeReplyTerm) -> String {
    match reply {
        SafeNativeReplyTerm::Ok(value) => encode_ok(operation, value),
        SafeNativeReplyTerm::Error { code, message, .. } => {
            format!("err {} {}", encode_text(&code), encode_text(&message))
        }
    }
}

/// Encodes a successful SafeNative value.
///
/// Inputs: operation id and success term.
/// Output: line-protocol success response.
/// Transformation: wraps selected operations in `Result` response forms and
/// serializes supported scalar, handle, and string-list values.
fn encode_ok(operation: &str, value: SafeNativeTerm) -> String {
    let result_wrapped = operation_returns_result(operation);
    match value {
        SafeNativeTerm::Unit => "ok_unit".to_string(),
        SafeNativeTerm::Int(value) if result_wrapped => format!("result_ok_int {value}"),
        SafeNativeTerm::Int(value) => format!("ok_int {value}"),
        SafeNativeTerm::Bool(value) if result_wrapped => format!("result_ok_bool {value}"),
        SafeNativeTerm::Bool(value) => format!("ok_bool {value}"),
        SafeNativeTerm::Text(value) if result_wrapped => {
            format!("result_ok_string {}", encode_text(&value))
        }
        SafeNativeTerm::Text(value) => format!("ok_string {}", encode_text(&value)),
        SafeNativeTerm::Handle { id, generation } if result_wrapped => {
            format!(
                "result_ok_handle {id} {generation} {}",
                encode_text(operation)
            )
        }
        SafeNativeTerm::Handle { id, generation } => {
            format!("ok_handle {id} {generation} {}", encode_text(operation))
        }
        SafeNativeTerm::List(values) => {
            let encoded = values
                .into_iter()
                .filter_map(|value| match value {
                    SafeNativeTerm::Text(text) => Some(encode_text(&text)),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(",");
            format!("ok_strings {encoded}")
        }
        _ => error_response(
            "safe_native_unsupported_reply",
            "unsupported SafeNative reply encoding",
        ),
    }
}

/// Returns whether a SafeNative operation lowers to a Terlan `Result`.
///
/// Inputs: operation id.
/// Output: `true` for operations whose successful replies are wrapped.
/// Transformation: matches the stable operation set that reports typed runtime
/// errors through `Result`.
fn operation_returns_result(operation: &str) -> bool {
    matches!(
        operation,
        "std.data.json.float"
            | "std.data.json.parse"
            | "std.data.json.stringify"
            | "std.data.json.get"
            | "std.data.json.length"
            | "std.data.json.at"
            | "std.data.json.as_string"
            | "std.data.json.as_int"
            | "std.data.json.as_float"
            | "std.data.json.as_bool"
    )
}

/// Encodes text for the SafeNative line protocol.
///
/// Inputs: UTF-8 text.
/// Output: base64 encoded text.
/// Transformation: encodes bytes without adding line breaks.
fn encode_text(value: &str) -> String {
    STANDARD.encode(value.as_bytes())
}

/// Builds an encoded SafeNative error response.
///
/// Inputs: stable error code and human-readable message.
/// Output: line-protocol error response.
/// Transformation: base64-encodes both fields so spaces are protocol-safe.
fn error_response(code: &str, message: &str) -> String {
    format!("err {} {}", encode_text(code), encode_text(message))
}
